### PR TITLE
Update the target platform's Maven dependencies to the latest available

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
Update these:

 - [com.google.code.gson](https://repo1.maven.org/maven2/com/google/code/gson/)
    - [gson](https://repo1.maven.org/maven2/com/google/code/gson/gson/) **[2.10](https://repo1.maven.org/maven2/com/google/code/gson/gson/2.10)** < [2.10.1](https://repo1.maven.org/maven2/com/google/code/gson/gson/2.10.1/)
 - [net.bytebuddy](https://repo1.maven.org/maven2/net/bytebuddy/)
    - [byte-buddy](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/) **[1.12.20](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.12.20)** < [1.12.21](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.12.21/)
    - [byte-buddy-agent](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/) **[1.12.20](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.12.20)** < [1.12.21](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.12.21/)
 - [org.assertj](https://repo1.maven.org/maven2/org/assertj/)
    - [assertj-core](https://repo1.maven.org/maven2/org/assertj/assertj-core/) **[3.23.1](https://repo1.maven.org/maven2/org/assertj/assertj-core/3.23.1)** < [3.24.1](https://repo1.maven.org/maven2/org/assertj/assertj-core/3.24.1/)
 - [org.mockito](https://repo1.maven.org/maven2/org/mockito/)
    - [mockito-core](https://repo1.maven.org/maven2/org/mockito/mockito-core/) **[4.10.0](https://repo1.maven.org/maven2/org/mockito/mockito-core/4.10.0)** < [4.11.0](https://repo1.maven.org/maven2/org/mockito/mockito-core/4.11.0/)

**Comment by merks** [comment]
@akurtakov 

These three fail:
```
[INFO] maven/mavencentral/com.google.code.gson/gson/2.10.1
[INFO] maven/mavencentral/org.assertj/assertj-core/3.24.1
[INFO] maven/mavencentral/org.mockito/mockito-core/4.11.0
```

In the summary files are they listed like this:
```
maven/mavencentral/com.google.code.gson/gson/2.10.1, , restricted, clearlydefined
maven/mavencentral/org.assertj/assertj-core/3.24.1, , restricted, clearlydefined
maven/mavencentral/org.mockito/mockito-core/4.11.0, , restricted, clearlydefined
```

What's the process now for getting those resolved?  If there is expected to be a significant delay, I could remove them from this PR and do them separately afterwards...  There are some OSGi libraries that need updating as well but last time that didn't work so I wanted to handle them separately.

**Comment by akurtakov** [comment]
We need them approved in iplab. There is a bot that runs every few hours . I see that https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/6161 is already under review. IMHO wait couple of hours and remove whatever is not yet approved from the PR after that.

**Comment by merks** [comment]
The following iplab issues are open for review:

- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/6159
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/6160
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/6161

**Comment by akurtakov** [comment]
All iplab issues approved, I've rerun license check and it's happy now. Build failure is due to the fact that test feature has to be touched to pick up the new dependencies.

**Comment by merks** [comment]
@akurtakov 

FYI, I noticed that these validation builds do signing:
```
11:56:48  [INFO] Signing jar: /home/jenkins/agent/workspace/latform.releng.aggregator_PR-791/eclipse.platform.ui/bundles/org.eclipse.e4.ui.workbench.swt/target/org.eclipse.e4.ui.workbench.swt-0.16.700-SNAPSHOT.jar
11:56:49  [INFO] Signing jar: /home/jenkins/agent/workspace/latform.releng.aggregator_PR-791/eclipse.platform.ui/bundles/org.eclipse.e4.ui.workbench.swt/target/org.eclipse.e4.ui.workbench.swt-0.16.700-SNAPSHOT-sources.jar
```
That has significant overhead that one could avoid to speed up the validation process...

**Pull request merged**
