### PR TITLE
Update Felix SCR to version 2.2.4

### PR DESCRIPTION
**Pull request by akurtakov**
Release notes:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310100&version=12352370

### CODE REVIEW

**Comment by sravanlakkimsetti** [comment]
This will require a touch in org.eclipse.equinox.core.feature.feature.group. Going ahead with the merge as the touch is required in another repository

**Comment by iloveeclipse** [comment]
https://ci.eclipse.org/releng/job/Builds/job/I-build-4.26/47/console
Build fails with 
```
01:03:38  [ERROR] Cannot resolve project dependencies:
01:03:38  [ERROR]   Software being installed: org.eclipse.equinox.sdk.product 4.26.0.qualifier
01:03:38  [ERROR]   Missing requirement: org.eclipse.equinox.compendium.sdk.feature.group 3.22.400.v20220720-2012 requires 'org.eclipse.equinox.p2.iu; org.apache.felix.scr [2.2.2,2.2.2]' but it could not be found
01:03:38  [ERROR]   Cannot satisfy dependency: org.eclipse.equinox.sdk.feature.group 3.23.600.v20221012-0834 depends on: org.eclipse.equinox.p2.iu; org.eclipse.equinox.compendium.sdk.feature.group [3.22.400.v20220720-2012,3.22.400.v20220720-2012]
01:03:38  [ERROR]   Cannot satisfy dependency: org.eclipse.equinox.sdk.product 4.26.0.qualifier depends on: org.eclipse.equinox.p2.iu; org.eclipse.equinox.sdk.feature.group 0.0.0
```

**Comment by akurtakov** [comment]
Looks like there is one more feature to touch. I'll do it now.

**Comment by iloveeclipse** [comment]
Another one? missing:
https://ci.eclipse.org/releng/job/Builds/job/I-build-4.26/49/console
```
[ERROR] Cannot resolve project dependencies:
08:56:16  [ERROR]   Software being installed: org.eclipse.equinox.sdk.product 4.26.0.qualifier
08:56:16  [ERROR]   Missing requirement: org.eclipse.equinox.server.core.feature.group 1.14.800.v20221011-0914 requires 'org.eclipse.equinox.p2.iu; org.apache.felix.scr [2.2.2,2.2.2]' but it could not be found
08:56:16  [ERROR]   Cannot satisfy dependency: org.eclipse.equinox.sdk.feature.group 3.23.600.v20221013-0547 depends on: org.eclipse.equinox.p2.iu; org.eclipse.equinox.server.core.feature.group [1.14.800.v20221011-0914,1.14.800.v20221011-0914]
08:56:16  [ERROR]   Cannot satisfy dependency: org.eclipse.equinox.sdk.product 4.26.0.qualifier depends on: org.eclipse.equinox.p2.iu; org.eclipse.equinox.sdk.feature.group 0.0.0
```

**Comment by akurtakov** [comment]
Yes, unfortunately we don't have easy way to catch these. Best effort is to go for require instead of import so we don't have to touch features in cases like that but there was some potential problem which I can't remember right now.

**Pull request merged**
