### PR TITLE
backport: Update bouncycastle to 1.76

### PR DESCRIPTION
**Pull request by gireeshpunathil**
Refs: https://github.com/advisories/GHSA-hr8g-6v94-x4m9

/cc @akurtakov

### CODE REVIEW

**Comment by akurtakov** [comment]
Please don't add me to backports. Old releases are done deal for me and I can't affort spending time on anything but next release.

**Comment by akurtakov** [comment]
Will this one be finished or it should be closed?

**Comment by gireeshpunathil** [comment]
> Will this one be finished or it should be closed?

I don't see a reason to close this. any committer in this repo with spare cycles to review could take this forward.

**Comment by akurtakov** [comment]
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/42b5209eb26da8bdf622e92843cad5e99e7ea320 moves to latest bouncycastle.

**Pull request closed without merging**
