### PR TITLE
publish 4.32 to maven central 

### PR DESCRIPTION
**Pull request by elsazac**
Publish to maven central 4.32

Update SDK4Mvn.aggr and properties.sh file

cc/ @MohananRahul

### CODE REVIEW

**Review by MohananRahul — APPROVED** [review]

**Comment by merks** [comment]
This looks good.  

There's actually no point waiting for a build because the only thing that uses are these jobs here:

https://ci.eclipse.org/releng/view/Publish%20to%20Maven/

If there's anything I can do to help, just let me know.

**Comment by elsazac** [comment]
> This looks good.
> 
> There's actually no point waiting for a build because the only thing that uses are these jobs here:
> 
> https://ci.eclipse.org/releng/view/Publish%20to%20Maven/
> 
> If there's anything I can do to help, just let me know.

@merks Thanks for the review. I will merge it right away.

**Comment by merks** [comment]
FYI, I use the SimRel Aggregation Analyzer Editor to get an overview of the mapping to POMs. 

image

I look for this with ** on them that represent things not yet present in any version at Maven Central.  So I see there are a small number of new things.  This view also helps me find broken dependencies.  I'm not suggesting you need to do anything, it's just an FYI.

Fortunately this job also ensures that all dependencies of each artifact resolve so that's automated too:

https://ci.eclipse.org/releng/view/Publish%20to%20Maven/job/RepositoryValidator/

**Comment by merks** [comment]
I see a release build has started:

https://ci.eclipse.org/releng/view/Publish%20to%20Maven/job/CBIaggregator/1014/parameters/

Very good!  😀

**Comment by elsazac** [comment]
CBI aggregator job has been successfully completed and I have closed all the three repositories JDT, PDE and Platform in the staging view.

**Pull request merged**
