### PR TITLE
JUnitTestRunnerInterceptor: Add missing dependency #1640

### PR DESCRIPTION
**Pull request by jukzi**
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1640

### CODE REVIEW

**Comment by laeubi** [comment]
> @akurtakov i don't know how to test this locally

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator#how-to-build-the-eclipse-sdk

**Comment by jukzi** [comment]
> https://github.com/eclipse-platform/eclipse.platform.releng.aggregator#how-to-build-the-eclipse-sdk

is there a way to only build swt?

**Comment by mickaelistria** [comment]
> is there a way to only build swt?

You can try reproducing the steps described in the Jenkinsfile for that.

**Comment by laeubi** [comment]
> > https://github.com/eclipse-platform/eclipse.platform.releng.aggregator#how-to-build-the-eclipse-sdk
> 
> is there a way to only build swt?

There are ways to run only parts of it, e.g. by specify `-Pbuild-individual-bundles` but if one is unsure running the full build is quite lengthy but most often the easiest choice for the beginners, I would just run it with test **enabled** and `-fae` option then you will see if only some tests fail (what I never got fully running locally) or if the test-run itself failed with the mentioned exception.

**Comment by jukzi** [comment]
> https://github.com/eclipse-platform/eclipse.platform.releng.aggregator#how-to-build-the-eclipse-sdk

that does not pass:
image

however that was after swt build:
image

however the tests are not executed so i started
```
cd C:\Users\jkubitz\platform-2023-12-01\git\eclipse.platform.releng.aggregator\eclipse.platform.swt
mvn -Pbuild-individual-bundles clean verify
```
image

and the tests are running ... does that proof anything?

**Comment by jukzi** [comment]
> You can undo your change and check if the SWT tests will fail. Then we will know for sure.

image

**Comment by akurtakov** [comment]
@jukzi Did this one helped any issue? I ask as it is causing extra warnings in the builds, e.g. https://ci.eclipse.org/pde/job/eclipse.pde/job/PR-991/1/console:
```
 Maven Artifact org.openclover:clover:4.5.1 @ /home/jenkins/agent/workspace/eclipse.pde_PR-991/.m2/repository/org/openclover/clover/4.5.1/clover-4.5.1.jar is not a bundle and will be ignored, automatic wrapping of such artifacts can be enabled with <pomDependencies>wrapAsBundle</pomDependencies> in target platform configuration.
```
If you can't make it clear and there is no proof that it actually improves anything I would ask you to remove it.

**Comment by laeubi** [comment]
Just in case I think it should eb an additioanl depednecy of the maven-surefire plugin NOT the build like in the example pom.xml where they seem to use it for some clover-maven-plugin, I still don't understand where we use clover so this can help but want to mention it.

**Comment by akurtakov** [comment]
What's the status here? I will prep a revert today if there is nothing else.

**Pull request merged**
