### PR TITLE
Add jakarta.inject-api / jakarta.annotation-api to isv build

### PR DESCRIPTION
**Pull request by laeubi**

### CODE REVIEW

**Comment by merks** [comment]
@laeubi 

FYI, ignore the license problem.  It's unrelated to your change.

**Comment by laeubi** [comment]
CI is fine so lets go for it...

**Comment by akurtakov** [comment]
This is still not fixed as the the same symbolic name jakarta.annotation-api is used for both versions which confuses the handcrafted script.

**Comment by laeubi** [comment]
> This is still not fixed as the the same symbolic name jakarta.annotation-api is used for both versions which confuses the handcrafted script.

Do you mean Tycho extra requirements or can you reference the script in question?

**Comment by laeubi** [comment]
@akurtakov another question: Can we somehow see this error in this build here as well?

**Comment by mickaelistria** [comment]
@laeubi do you mean logs from https://download.eclipse.org/eclipse/downloads/drops4/I20231012-1800/logs.php#javadoc ?

**Comment by akurtakov** [comment]
I haven't looked enough into how can we make the jenkins build fail if javadoc build fails if this is the question.

**Comment by laeubi** [comment]
I have now created:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1439

**Comment by laeubi** [comment]
@mickaelistria I mean what ever fails and needs fixing here :-)

**Pull request merged**
