### PR TITLE
Explicit block for Jetty in target definition fil

### PR DESCRIPTION
**Pull request by vogella**
Helps to easily identify the Jetty dependencies which are frequently
updated.

### CODE REVIEW

**Comment by vogella** [comment]
Looks like this:

image

@akurtakov and @mickaelistria WDYT?

**Comment by mickaelistria** [comment]
I think it's indeed a bit better to have such groups. However, we need to ensure there are no extra constraints and drawbacks with that. @laeubi would there be any reason to *not* use groups (performance drawback, resolution inconsistencies...)?

**Comment by laeubi** [comment]
All items of a group share the same settings for 

- includeDependencyScope
- includeSource
- missingManifest

and probably default BND settings. So if thats fine to apply to all there is no drawback in grouping them.

**Comment by laeubi** [comment]
> which are frequently updated

Just in case not noted that functionality, selecting a dependency and click the Update button will look for the latest dependency in the maven repository.

**Comment by mickaelistria** [comment]
The question is more the other way round (although I didn't express it clearly): is there any drawback in turning 1 single group into several ones?

**Pull request merged**
