### PR TITLE
Remove generation of unused testProperties.php file

### PR DESCRIPTION
**Pull request by HannesWell**
For the generated `testProperties.php` I couldn't find any reference.

And although the file is indexed with a size of 1.4kB I cannot see any content and if I try to download it with curl it's empty:
- https://download.eclipse.org/eclipse/downloads/drops4/I20241027-1800/testresults/ep434I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17/
- https://download.eclipse.org/eclipse/downloads/drops4/I20241027-1800/testresults/ep434I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17/testProperties.php

@akurtakov or @laeubi can you say more about this file or is it probably save to stop generating it?

### CODE REVIEW

**Comment by akurtakov** [comment]
I have no idea, @sravanlakkimsetti  maybe you can answer?

**Comment by HannesWell** [comment]
> I have no idea, @sravanlakkimsetti maybe you can answer?

@sravanlakkimsetti or maybe @MohananRahul if you don't have objections, I'll submit this tomorrow, Wednesday, and we'll see if my assumption is correct.

**Comment by MohananRahul** [comment]
> > I have no idea, @sravanlakkimsetti maybe you can answer?
> 
> @sravanlakkimsetti or maybe @MohananRahul if you don't have objections, I'll submit this tomorrow, Wednesday, and we'll see if my assumption is correct.

I’m also not sure about this (noticed the same issue in the archive builds as well), but let’s go ahead with it and see how it unfolds.

**Comment by HannesWell** [comment]
> I’m also not sure about this (noticed the same issue in the archive builds as well), but let’s go ahead with it and see how it unfolds.

Ok, then let's try it and hope for the best. 
Thanks.

**Comment by HannesWell** [comment]
> > I’m also not sure about this (noticed the same issue in the archive builds as well), but let’s go ahead with it and see how it unfolds.
> 
> Ok, then let's try it and hope for the best.

After inspecting the logs of the latest I-builds, e.g. https://download.eclipse.org/eclipse/downloads/drops4/I20241101-1800/, I cannot find any defects. So I think this removal was successful.

**Pull request merged**
