### PR TITLE
Remove the org.eclipse.rcp.configuration feature and all its references

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2109

### CODE REVIEW

**Comment by merks** [comment]
@iloveeclipse  @akurtakov @MohananRahul 

I assume you folks have no concerns about removing this.  With PDE build removing its use of this, I think this has become garbage that can be collected.  Okay?

**Comment by akurtakov** [comment]
None from me.

**Review by HannesWell — APPROVED** [review]
Looks good to me. 
I also found no other reference to org.eclipse.rcp.configuration in the SDK and think it's great to get rid of another ancient effectively unused piece of baggage.

**Comment by merks** [comment]
Let's live dangerously and see what happens with the next I-Build.

**Pull request merged**
