### PR TITLE
New and Noteworthy 4.31

### PR DESCRIPTION
**Pull request by alshamams**

### CODE REVIEW

**Review by elsazac — APPROVED** [review]
LGTM

**Review by sravanlakkimsetti — APPROVED** [review]

**Comment by stephan-herrmann** [comment]
A tiny detail: both original PRs https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/133 and https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1828 contained a file eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/whatsNew/images/resource-demo-code.txt to which the same named image links for those who want to copy&paste the code.
I don't see this file in this PR here. Intentionally?

**Comment by alshamams** [comment]
> A tiny detail: both original PRs [eclipse-platform/www.eclipse.org-eclipse#133](https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/133) and #1828 contained a file eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/whatsNew/images/resource-demo-code.txt to which the same named image links for those who want to copy&paste the code. I don't see this file in this PR here. Intentionally?

@stephan-herrmann , thanks for spotting this. I am following the script in https://github.com/eclipse-platform/www.eclipse.org-eclipse/tree/master/news/scripts to integrate all the N&Ns into this repo. Looks like the script ignores the txt files. 

How important is this change for you? I ask this because there may be a PMC approval required now in case of a rebuild. If we want to get this in then can you adjust #1828 to contain only the missing piece.

**Comment by alshamams** [comment]
While we are at it I thought of mentioning a fixup that I performed in your N&N: the target link for `org.eclipse.jdt.annotation.Owning` is either non-existent or broken. I fixed it by converting it to a non-link. Hope this is fine by you. @stephan-herrmann

**Pull request merged**
