### PR TITLE
Ybuild Failure issue Resolution:

### PR DESCRIPTION
**Pull request by MohananRahul**
changes Done for below files in Jenkins folder

1. ep427Y_unit_cen64_gtk3_java17 : change pipelineJob ep425 to ep427
2. ep427Y_unit_cen64_gtk3_java19 : change pipelineJob ep425 to ep427
3. ep427Y_unit_cen64_gtk3_java20 : change pipelineJob ep425 to ep427 and java20
4. ep427Y_unit_macM1_java17 : change pipelineJob ep425 to ep427
5. ep427Y_unit_mac64_java17 : change pipelineJob ep425 to ep427
6. Y_build : added containers 'Trigger tests'

Please verify

### CODE REVIEW

**Comment by MohananRahul** [comment]
@sravanlakkimsetti Please Review the PR.

**Comment by sravanlakkimsetti** [comment]
There is a conflict in one of the files. can you please resolve the conflict?

**Comment by SDawley** [comment]
Instead of keeping the version hardcoded so someone has to remember to update every release, it might be better to use the JobDSL.json like I did with 
[JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java20.groovy](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/709ba47d9c9a5f5f82ec651ecd8b737a9cc8f0b1/JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java20.groovy#L1-L8)

After these changes are merged https://ci.eclipse.org/releng/job/Create%20Jobs/ will have to be run again, does Mohanan have access? Otherwise Sravan or I can do it.

**Comment by MohananRahul** [comment]
Created new PR #841. Added Suggested changes for YBuilds, using JobDSL Versioning.

**Pull request closed without merging**
