### PR TITLE
Fix platform javadoc build

### PR DESCRIPTION
**Pull request by akurtakov**
Broken in
https://download.eclipse.org/eclipse/downloads/drops4/I20231205-0520/compilelogs/platform.doc.isv.javadoc.txt

### CODE REVIEW

**Comment by akurtakov** [comment]
Pushing in order to try getting docs build correct tomorrow. Verification build breakage looks related to https://github.com/eclipse-pde/eclipse.pde/pull/980

**Comment by iloveeclipse** [comment]
Triggered rebuild https://ci.eclipse.org/platform/job/eclipse.platform.releng.aggregator/job/PR-1639/2/

**Comment by iloveeclipse** [comment]
`Execution exception: Java heap space`
But the build was almost through => merging.

**Comment by akurtakov** [comment]
Thanks for pushing it @iloveeclipse . Amongst all other things I forgot to hit the button.

**Pull request merged**
