### PR TITLE
Add linux.riscv64 environment to eclipse-platform-parent and publish linux.riscv64 artifacts

### PR DESCRIPTION
**Pull request by HannesWell**
Similiarly like it was done for Windows on ARM:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1917
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2017

Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2310.

@yuzibo FYI

### CODE REVIEW

**Comment by HannesWell** [comment]
@merks we also need something similar to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1953.
But when I add a `<configurations operatingSystem="linux" windowSystem="gtk" architecture="riscv64"/>` the Aggregator Editor cannot open the file anymore.
I'll therefore hold that off until we have support for `riscv64` architectures. Can you tell if this has to be added explicitly or is this inherited at some point in time?

**Comment by yuzibo** [comment]
> 
> @yuzibo FYI



> Similiarly like it was done for Windows on ARM:
> 
> * [Add win32.aarch64 environment to eclipse-platform-parent and publish win32.aarch64 artifacts #1917](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1917)
> * [[I-Build] Copy built products for Windows on Arm to publication area #2017](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2017)
> 
> Part of #2310.
> 
> @yuzibo FYI

Thank you. I will add this to the [summary](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2310) list also.

**Comment by merks** [comment]
@HannesWell 

I change to the *.aggr made the job fail:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2397

The validation fails:

```
Cannot complete the install because one or more required items could not be found. Software being installed: validationSet_main 1.0.0 Missing requirement for filter properties ~= $0: org.eclipse.equinox.executable 3.8.2700.v20240924-2302 requires 'org.eclipse.equinox.p2.iu; org.eclipse.equinox.launcher.gtk.linux.riscv64 [1.2.1200.v20240924-2302,1.2.1200.v20240924-2302], filter=(&(osgi.arch=riscv64)(osgi.os=linux)(osgi.ws=gtk))' but it could not be found Cannot satisfy dependency: mappedRepo_download.eclipse.org_eclipse_updates_4.34-I-builds 1.0.0 depends on: org.eclipse.equinox.p2.iu; org.eclipse.equinox.executable 0.0.0 Cannot satisfy dependency: validationSet_main 1.0.0 depends on: org.eclipse.equinox.p2.iu; mappedRepo_download.eclipse.org_eclipse_updates_4.34-I-builds [1.0.0,1.0.0]
Missing requirement for filter properties ~= $0: Eclipse Platform Launcher Executables for Multi-Architecture Builds 3.8.2700.v20240924-2302 (org.eclipse.equinox.executable 3.8.2700.v20240924-2302) requires 'org.eclipse.equinox.p2.iu; org.eclipse.equinox.launcher.gtk.linux.riscv64 [1.2.1200.v20240924-2302,1.2.1200.v20240924-2302], filter=(&(osgi.arch=riscv64)(osgi.os=linux)(osgi.ws=gtk))' but it could not be found

InstallableUnit(org.eclipse.equinox.launcher.gtk.linux.riscv64 [1.2.1200.v20240924-2302,1.2.1200.v20240924-2302]) is required by:
  ValidationSet(main)
    Contribution(sdk_http)
      MappedRepository(https://download.eclipse.org/eclipse/updates/4.34-I-builds)
        InstallableUnit(org.eclipse.equinox.executable 3.8.2700.v20240924-2302)
```
I see this requirement in the IU org.eclipse.equinox.executable:
```
    <required namespace='org.eclipse.equinox.p2.iu' name='org.eclipse.equinox.launcher.gtk.linux.riscv64' range='[1.2.1200.v20240924-2302,1.2.1200.v20240924-2302]'>
      <filter>
        (&amp;(osgi.arch=riscv64)(osgi.os=linux)(osgi.ws=gtk))
      </filter>
    </required>
```
How long do we think we'll be in this state where there a requirements that can't be satisfied?  If that's a while, then I should revert that commit to the SDK4Mvn.aggr...

**Comment by HannesWell** [comment]
> How long do we think we'll be in this state where there a requirements that can't be satisfied? If that's a while, then I should revert that commit to the SDK4Mvn.aggr...

I hope it isn't long.
In general I believe we have the most difficult parts in place and just have to plugin in the missing pieces. I assume this to be a big one, but I first have to investigate why this is failing.

**Comment by HannesWell** [comment]
I have now investigated the failure in detail and found out that in the end the p2-baseline replacement removed the linux.riscv64 root-files in the o.e.equinox.executable.feature.
I have created https://github.com/eclipse-equinox/equinox/pull/680 to fix that and explained it in detail there.
@yuzibo I have added the latter to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2310.

**Comment by HannesWell** [comment]
Testing was successful and this PR is now in it's final state.
After the build has succeeded, I'll submit this and want to start a new I-build immediately to verify everything works as expected.

**Comment by HannesWell** [comment]
Just started https://ci.eclipse.org/releng/job/Builds/job/I-build-4.34/50/.

**Comment by yuzibo** [comment]
Thanks!

**Comment by HannesWell** [comment]
> Just started https://ci.eclipse.org/releng/job/Builds/job/I-build-4.34/50/.

This build succeeded and the `org.eclipse.equinox.launcher.gtk.linux.riscv64` and `org.eclipse.swt.gtk.linux.riscv64` fragments are now available in the corresponding I-build repository.
The new download links also all work as expected.

> Thanks!

You're welcome. And thanks for all your contributions.

**Pull request merged**
