### PR TITLE
Update the java paths using 8dot3 notation

### PR DESCRIPTION
**Pull request by sravanlakkimsetti**
tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/756

### CODE REVIEW

**Comment by sravanlakkimsetti** [comment]
> Out of curiosity, I wonder if a path like `C:\\PROGRA~1\\ECLIPS~1\\` could "change" if something else that starts with ECLIPS and came alphabetically before `Eclipse Adoptium` was installed?

it is based on time. if something else gets installed it will be ECLIPS~2. by the way you actually get these file names using `dir /x`. I used `dir /x` to get the actual names and then updated the script

**Comment by akurtakov** [comment]
So ant runs with Java 11 but uses java 17 to actually execute the tests?

**Comment by merks** [comment]
@sravanlakkimsetti  I see.  It would also work to use `\\ ` to escape the single space (the same way that `\\\\` is used to escape the single `\` right?

**Comment by sravanlakkimsetti** [comment]
> So ant runs with Java 11 but uses java 17 to actually execute the tests?

yes that is correct

**Comment by sravanlakkimsetti** [comment]
> @sravanlakkimsetti I see. It would also work to use `\\ ` to escape the single space (the same way that `\\\\` is used to escape the single `\` right?

In theory yes that should work but need to test on windows platform

**Pull request merged**
