### PR TITLE
More plugins to join Y-Builds from their BETA_JAVA24 branch

### PR DESCRIPTION
**Pull request by stephan-herrmann**
include:
* jdt.ui
* jdt.debug

Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2505

### CODE REVIEW

**Comment by merks** [comment]
> This error:
> 
> ```
> 13:53:00  [ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:4.0.9:archive-repository (default-archive-repository) on project eclipse.platform.repository: Error packing p2 repository: Problem creating zip: Execution exception: Java heap space -> [Help 1]
> ```
> 
> doesn't look like it is caused by my changes.

This is a recurring annoying random problem.

**Comment by stephan-herrmann** [comment]
> This is a recurring annoying random problem.

So is this the bottom of the resources question during the releng BoF? :sunglasses:

**Comment by merks** [comment]
Yes this was a BoF complaint.

**Comment by stephan-herrmann** [comment]
My simple change should still be safe, even if creating the final zip failed, no?

**Comment by merks** [comment]
I started a new build 

https://ci.eclipse.org/platform/job/eclipse.platform.releng.aggregator/job/PR-2506/2/

eventually it should work. Ocean levels may rise.

**Comment by stephan-herrmann** [comment]
> I started a new build
> 
> https://ci.eclipse.org/platform/job/eclipse.platform.releng.aggregator/job/PR-2506/2/

Thanks, apparently you have the golden mouse to do the lucky click

> Ocean levels may rise.

Are you referring to effects of the moon or of mankind?
 
> But yes you could ignore the failure. 😨

Me ignoring the failure doesn't get the change merged ... may I ask you?

**Pull request merged**
