### PR TITLE
sdk.tests/testScripts/test.xml: Kill msedgewebview2.exe processes

### PR DESCRIPTION
**Pull request by sratz**
To troubleshoot #2651.

### CODE REVIEW

**Review by akurtakov — COMMENTED** [review]
I can neither approve nor request any change here as I have no idea what the process is, nor about the syntax of `taskkill` nor how it helps, sorry.

**Comment by jukzi** [comment]
i'd say its worth a try, just test it immediately and revert if it does not help

**Comment by sratz** [comment]
> just test it immediately

https://ci.eclipse.org/releng/job/AutomatedTests/job/ep435I-unit-win32-x86_64-java17/ takes the I-Build number as an input and also takes the `build.xml` from that. So I suppose we'd have to wait for Tomorrow's build.

Unless there is some trick to use `build.xml` from git but test against Today's build?

**Comment by akurtakov** [comment]
@sratz In such cases you could/should start an extra I-build yourself.

**Comment by fedejeanne** [comment]
> @sratz In such cases you could/should start an extra I-build yourself.

Tried that and failed --> https://ci.eclipse.org/releng/job/AutomatedTests/job/ep435I-unit-win32-x86_64-java17/25/

**Comment by fedejeanne** [comment]
> > @sratz In such cases you could/should start an extra I-build yourself.
> 
> Tried that and failed --> https://ci.eclipse.org/releng/job/AutomatedTests/job/ep435I-unit-win32-x86_64-java17/25/

but I did it too soon anyway. We should merge this PR first. One sec.

**Review by fedejeanne — APPROVED** [review]
Let's try it

**Comment by fedejeanne** [comment]
> > just test it immediately
> 
> https://ci.eclipse.org/releng/job/AutomatedTests/job/ep435I-unit-win32-x86_64-java17/ takes the I-Build number as an input and also takes the `build.xml` from that. So I suppose we'd have to wait for Tomorrow's build.
> 
> Unless there is some trick to use `build.xml` from git but test against Today's build?

I see what you meant now. I triggered an I-BUILD with a fake "current" ID but it failed...

image

So what we need is to:
1. Do the "nightly" build again to create the appropriate "drop" (@merks ?)
2. Trigger the [tests](https://ci.eclipse.org/releng/job/AutomatedTests/job/ep435I-unit-win32-x86_64-java17/) with the correct ID.

**Comment by sratz** [comment]
> Let's try it

https://ci.eclipse.org/releng/job/AutomatedTests/job/ep435I-unit-win32-x86_64-java17/27/ will show no difference. As said, the build scripts are taken from the I-Build as well.

We have to wait for a new I-build first.
I have started https://ci.eclipse.org/releng/job/Builds/job/I-build-4.35/33/

**Comment by fedejeanne** [comment]
It just occurred to me: this PR will kill the process **before** running the tests, but the error happens because the clean-up task for `AutomatedConfiguratorSuite` is trying to delete the user-data folder **after** the test finished (but before the process is done). This would mean that this PR won't solve the problem.

Or am I seeing it wrong?

**Comment by sratz** [comment]
The setup is a bit confusing.

It's not the `cleanup` task that is failing, but the `setup` task of the subsequent test plugin, which cleans up the workspace of the previous test plugin.

**Pull request merged**
