### PR TITLE
Merge eclipse.platform.resources into eclipse.platform repository

### PR DESCRIPTION
**Pull request by laeubi**

### CODE REVIEW

**Comment by akurtakov** [comment]
Let's get real test then :)

**Comment by iloveeclipse** [comment]
We have a big problem: I don't know how that merge was done, but there is NO GIT HISTORY MORE at all, on any resource related code.

**Comment by iloveeclipse** [comment]
This is a huge issue because it removes any context information, any bisecting of any change impossible.

**Comment by iloveeclipse** [comment]
We lost a *decade* of information.

**Comment by merks** [comment]
Oh dear yes, that's very bad!  It looks squashed:

image

And I think that's more than two decades of information.  We must repair this before moving on!

**Comment by laeubi** [comment]
Can we please investigate this here: https://github.com/eclipse-platform/eclipse.platform/pull/76 as this PR has nothing to do with the merge at all, at least there it says that "merged 4,181 commits into [eclipse-platform:master](https://github.com/eclipse-platform/eclipse.platform)"

**Pull request merged**
