### PR TITLE
Update RELEASE.md

### PR DESCRIPTION
**Pull request by bravesasha**
Fix typo

### CODE REVIEW

**Comment by akurtakov** [comment]
Would you please sign the ECA https://www.eclipse.org/legal/eca/ ? without it we can't accept anything from you.

**Comment by laeubi** [comment]
I tend to close this, I'm not sure what the intention of the author is to open hundreds of questionable "Fix Typo" things but I have seen a lot of them and they more look like automatically generated (by AI?) than real contributions because the author care about the project.

**Comment by bravesasha** [comment]
> I tend to close this, I'm not sure what the intention of the author is to open hundreds of questionable "Fix Typo" things but I have seen a lot of them and they more look like automatically generated (by AI?) than real contributions because the author care about the project.

You are wrong, there is no AI here. I just wanted to help the project, since I have no professional development skills, I try to find errors in the documentation, I agree, it does not always work. If you don't like it, I understand, I'm sorry, it won't happen again from my side

**Comment by akurtakov** [comment]
If you want to contribute to the project:
* please sign the ECA as requested in previous comment
* Do not create merge commits but rather rebase on too of master and force push to your branch.

**Comment by bravesasha** [comment]
Sorry for not replying right away. I have already signed the CLA

**Comment by bravesasha** [comment]
Please explain how I can make sure that I really signed the CLA. There should be a green checkmark next to the Eclipse Contributor Agreement?

**Comment by merks** [comment]
It looks like you maybe used some mangled version of your email address in the commit:

image

Is this page reachable for you?

https://api.eclipse.org/git/eca/status/gh/eclipse-platform/eclipse.platform.releng.aggregator/2204

**Comment by bravesasha** [comment]
I just went into Githu settings and noticed that I still have one default email with this message:

Not visible in emails
This email will not be used as the 'from' address for web-based Git operations, e.g., edits and merges. We will instead use 122097069+bravesasha@users.noreply.github.com.

**Comment by merks** [comment]
A commit like this cannot be properly associated with your ECA-registered email.

image

I know you don't want to be spammed, but if you want to contribute, you commits need to be associated with an email address for which there is an associated ECA.

**Comment by bravesasha** [comment]
Sorry. Please tell me how I can solve this issue. How do I link my primary email?

**Comment by bravesasha** [comment]
I think I already found the solution. Please check again

**Comment by merks** [comment]
I think that unless you push a new commit (just one, rebased on master) for which the email address isn't mangled it's not going to work.

**Comment by bravesasha** [comment]
Maybe I should delete this commit and create a new one. Since I do not work through the terminal, but directly?

**Comment by merks** [comment]
Yes.  I think that if you rename your old branch, create a new branch based on master with the same name as you used this PR, you can then make changes, commit them, and force push them to your fork's branch to overwrite the commit that's there and that will update this PR.

**Comment by merks** [comment]
Note too that it's generally expect that a PR will have a single commit

https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#creating-a-pull-request

So please force push a single commit.

**Comment by SougandhS** [comment]
> Maybe I should delete this commit and create a new one. Since I do not work through the terminal, but directly?
@bravesasha   I have faced the same issue, the solution is to change your github username and email to the one which was used to register ECA. ie the Author and Committer id should be same

**Comment by bravesasha** [comment]
thanks for the advice

**Pull request closed without merging**
