### PR TITLE
Revert "Update Comparator repo and eclipse run repo to 4.31-I-builds repo"

### PR DESCRIPTION
**Pull request by MohananRahul**
Reverts eclipse-platform/eclipse.platform.releng.aggregator#1592 PR, Still we don't have stable build and will create PR again after stable build

### CODE REVIEW

**Comment by akurtakov** [comment]
Push in order to try getting "good" 4.31 build.

**Comment by laeubi** [comment]
Can someone please explain how this is supposed to work? I think I already asked last time but should the comparator repo not simply copied from last I builds to the new URL so we dont need to switch back and forth?

**Comment by cdietrich** [comment]
the composite in https://download.eclipse.org/eclipse/updates/4.31-I-builds/ does not seem to be updated though

**Comment by akurtakov** [comment]
The add to composite stage failed https://ci.eclipse.org/releng/job/Builds/job/I-build-4.31/4/console . Note that is totally unrelated to the change here.

**Pull request merged**
