### PR TITLE
Update ECJ to RC1 version from I20230524-0600 (same as I202305250350)

### PR DESCRIPTION
**Pull request by iloveeclipse**
This version contains ECJ changes made after M3 build, no other ECJ changes are planned as of today.

### CODE REVIEW

**Comment by iloveeclipse** [comment]
OK, looks like we only have "final" ECJ versions in https://repo.eclipse.org/content/repositories/eclipse-staging/org/eclipse/jdt/ecj/, so that PR is too early & has to wait for RC1.

**Comment by MohananRahul** [comment]
> @MohananRahul : I would expect that after RC1 is announced, the ecj build `3.34.0.v20230523-1233` (which is [offered on RC1 page](https://download.eclipse.org/eclipse/downloads/drops4/S-4.28RC1-202305250350/)) would appear also on https://repo.eclipse.org/content/repositories/eclipse-staging/org/eclipse/jdt/ecj/.
> 
> But I don't see it there. Is this just timing issue, or do we miss some steps in RC1 propagation?

It was planned to run on Monday , @mpalat Could you please run "[copyAndDeployJDTCompiler](https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/) job" I already configured it.

**Comment by MohananRahul** [comment]
@iloveeclipse please merge.

**Comment by iloveeclipse** [comment]
Let it buid once.
https://ci.eclipse.org/platform/job/eclipse.platform.releng.aggregator/job/PR-1085/3/console

**Pull request merged**
