### PR TITLE
Update Eclipse.icns to match Apple UI Guideline

### PR DESCRIPTION
**Pull request by BeckerWdf**
Fixes: https://github.com/eclipse-platform/eclipse.platform.ui/issues/1247

### CODE REVIEW

**Review by merks — APPROVED** [review]
Thanks for tackling this.

**Comment by BeckerWdf** [comment]
I see that "Today is a freeze day". Is this also relevant for this kind of change? If yes, when can we merge this again?

**Comment by laeubi** [comment]
I don't know who is responsible for eclipse artwork ... and when such things should be merged now or for next release, but in general one should not have **code** changes so maybe images are ok?

**Comment by merks** [comment]
@akurtakov 

I would personally prefer to see this merged now.  EPP the analogous changes pending which I assume will also be done for M3...

**Comment by akurtakov** [comment]
I have zero Mac knowledge to estimate the importance of it. As Eclipse is supposed to be follow native LnF the change makes sense to me so take that as +0.5 .

**Comment by merks** [comment]
@BeckerWdf 

Go for it!  👍

**Pull request merged**
