### PR TITLE
Update JUnit to 5.9.1

### LINKED ISSUE #585: Update JUnit to 5.9.1

### PR DESCRIPTION
**Pull request by jjohnstn**
- fixes #585

### CODE REVIEW

**Review by mickaelistria — CHANGES_REQUESTED** [review]
Looks like you also need to change the range for the junit-jupiter-api the eclipse-junit-tests feature as well.

**Comment by jjohnstn** [comment]
Will that not be handled by the other pull which needs to be merged first? https://github.com/eclipse-platform/eclipse.platform.releng/pull/116

**Comment by mickaelistria** [comment]
Actually, this one has to be merged first. Then, once the .target is updated, we'll merge https://github.com/eclipse-platform/eclipse.platform.releng/pull/116 to get this feature updated.

**Review by mickaelistria — APPROVED** [review]

**Comment by jjohnstn** [comment]
Thanks Mickael.

**Pull request merged**
