### PR TITLE
Update EMF dependencies to EMF 2.33 M1

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
@akurtakov

These changes are needed to align what the Platform consumes and redistributes from EMF with what EMF has already contributed to SimRel 2023-03 M1.

**Comment by akurtakov** [comment]
Please merge as soon as verification build succeeds.

**Comment by akurtakov** [comment]
Actually, I-build starts in 4mins so I'll merge this one so we have it earlier.

**Comment by akurtakov** [comment]
> Sorry I'm a bit late. There was no issue open for this release cycle and I didn't get home until last night...

Just like most of us :)

**Pull request merged**
