### PR TITLE
Add bndtools API for templating

### PR DESCRIPTION
**Pull request by laeubi**
Lets see if we can have license checks here...

### CODE REVIEW

**Comment by merks** [comment]
Merged so I can regenerate orbit and platform report tomorrow.

**Comment by merks** [comment]
I should note that when I regenerated Orbit to include the additions from this PR, it opened these iplab issues:

- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11813
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11814

Both are current blocked requiring manual intervention, i.e, `IP Team Review Needed `.

So the fact that https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1611#issuecomment-1839438835 says everything is vetted is **false**.

**Comment by laeubi** [comment]
I think the vetting does not work for target only projects :-\

**Pull request merged**
