### PR TITLE
Update bouncycastle castle to 1.78

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
@akurtakov 

This looks like an infrastructure problem.  Firstly these things resolve:

image

And secondly they are both reviewed and approved:

[maven/mavencentral/org.bouncycastle/bcpg-jdk18on/1.78](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14236)
[maven/mavencentral/org.bouncycastle/bcpg-jdk18on/1.78](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14237)

Perhaps a problem because these were published to Maven Central literally just a few hours ago so maybe not mirrored everywhere...

**Comment by merks** [comment]
@akurtakov @msohn 

FYI, the problem here is that the latest versions have changed the bundle symbolic name:

image

And there was one place that this name was being used in a pom.

Looking at SimRel, all the requirements on these bundles are package requirements, so that's a good thing:

image

It will be interesting to see which version ends up in SimRel...

**Comment by merks** [comment]
@msohn @tomaswolf

When I tried to update EGit/JGit to the new versions there are errors:

image

I expected there would a problem when trying to update Oomph to use exclusively the newer bundles.

@akurtakov 

I'm reluctant to merge this change until we hear back from the EGit folks because I've already seen runtime excepts when combination of 1.77 and 1.78 are installed/used.

**Comment by akurtakov** [comment]
@merks with change in jgit done, should we merge this one?

**Comment by merks** [comment]
I don’t think this is submitted yet. 

https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1192750

My concern here is that when we commit this, do a new build, update to it, that the ide may have errors in the pgp processing.  This I saw in my oomph ide trying to update to these versions and the running the catalog generator. 

It the ide has broken pgp processing, then it can no longer update to fix the problem. So probably better to err on the side of caution and wait for an actual egit build with the new versions. 

I’m hoping the egit m1 contribution tomorrow will have picked up the new version.

**Comment by merks** [comment]
FYI, I see the issue is resolved now, but I'm monitoring the content here to see what is actually being updated with new builds:

https://download.eclipse.org/egit/

**Comment by tomaswolf** [comment]
> FYI, I see the issue is resolved now, but I'm monitoring the content here to see what is actually being updated with new builds:
> 
> https://download.eclipse.org/egit/

There is some changes in EGit, too, but currently we're having build problems. Once [Gerrit change 1192806](https://eclipse.gerrithub.io/c/eclipse-egit/egit/+/1192806) is in, we should have a new EGit repo that includes the new JGit.

**Comment by merks** [comment]
@tomaswolf 

For what it's worth, I had to add these two imports in the IDE because of complaints about missing things or indirectly required classes not being visible:

image

I.e., without those two, I have these errors in the workspace:

image

**Comment by tomaswolf** [comment]
@merks: looks like your setup is corrupted.

1. The org.bouncycastle.openpgp package import should already be there; compare the [current master version](https://eclipse.gerrithub.io/plugins/gitiles/eclipse-egit/egit/+/refs/heads/master/org.eclipse.egit.core/META-INF/MANIFEST.MF#65).
2. The org.apache.sshd... package import is wrong. I never needed that, and I don't have any errors in my Eclipse workspace. The JGit SSH support based on Apache MINA SSHD is supposed to hide the upstream interfaces completely. If it doesn't that would be an error in JGit.

**Comment by iloveeclipse** [comment]
@merks : not sure if it is my personal issue right now, but with latest nightly SDK build I see this error trying to open "About -> "
```
eclipse.buildId=4.32.0.I20240409-1800
java.version=21.0.2-13
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64 -data /data/4x_platform_workspace

org.eclipse.core.jobs
Error
Wed Apr 10 11:33:43 CEST 2024
An internal error occurred during: "Loading Bundle Data...".

java.lang.NoClassDefFoundError: org/bouncycastle/util/Iterable
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:293)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:774)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:691)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:657)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:637)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:616)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:348)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:499)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:174)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.eclipse.equinox.internal.p2.ui.KeySigningInfoFactory.getBundlePoolArtficactPGPSigningDetails(KeySigningInfoFactory.java:155)
	at org.eclipse.equinox.internal.p2.ui.KeySigningInfoFactory$1.<init>(KeySigningInfoFactory.java:43)
	at org.eclipse.equinox.internal.p2.ui.KeySigningInfoFactory.getAdapter(KeySigningInfoFactory.java:42)
	at org.eclipse.core.internal.adapter.AdapterFactoryProxy.lambda$5(AdapterFactoryProxy.java:111)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.eclipse.core.internal.adapter.AdapterFactoryProxy.getAdapter(AdapterFactoryProxy.java:111)
	at org.eclipse.core.internal.runtime.AdapterManager.lambda$7(AdapterManager.java:259)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1685)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:272)
	at org.eclipse.ui.internal.about.AboutPluginsPage.lambda$0(AboutPluginsPage.java:344)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.util.Iterable cannot be found by bcpg-jdk18on_1.78.0
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:562)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:557)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:174)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 35 more
```

Looks like I got the latest 1.78 version via https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/nightly/latest

**Comment by merks** [comment]
Yes, this is precisely the problem I'm hoping to avoid affecting a larger group of people.

But I don't know how 1.78.0 is ending up in your installation because that's not the version in the SDK repo:

image

Until there is a new EGit/JGit build which is locking in the older 1.78 version, we have a problem because the combination of versions does not work well.

This is also why I have not promoted the orbit aggregation nightly to a milestone...

So one might use https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/milestone/latest to avoid the issue?

**Comment by iloveeclipse** [comment]
> But I don't know how 1.78.0 is ending up in your installation because that's not the version in the SDK repo

I install few extra items that needed for platform tests, like org.easymock, org.mockito etc. They somehow pull in the 1.78 version.

> So one might use https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/milestone/latest to avoid the issue?

I will try that, thanks.

**Comment by merks** [comment]
FYI, this table provides a nice summary of the contents of the most significant repositories:

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/table.html

You can easily see which things are already updated in nightly/latest but not yet in milestone/latest (and similarly for other other columns).

**Comment by iloveeclipse** [comment]
With https://github.com/eclipse-platform/eclipse.platform.ui/pull/1809 I can setup my SDK to almost perfect state, except that there are JGit/Egit dependencies that can't be resolved because jgit needs old hamcrest & old jetty :-(

**Comment by tomaswolf** [comment]
EGit builds are running into the same exception as @iloveeclipse .
```
!ENTRY org.eclipse.ui 4 0 2024-04-10 19:33:21.749
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NoClassDefFoundError: org/bouncycastle/util/Iterable
	at org.eclipse.jgit.gpg.bc.internal.BouncyCastleGpgKeyLocator.findPublicKeyInPubring(BouncyCastleGpgKeyLocator.java:644)
	at org.eclipse.jgit.gpg.bc.internal.BouncyCastleGpgKeyLocator.findSecretKey(BouncyCastleGpgKeyLocator.java:442)
	at org.eclipse.jgit.gpg.bc.internal.BouncyCastleGpgSigner.locateSigningKey(BouncyCastleGpgSigner.java:120)
	at org.eclipse.jgit.gpg.bc.internal.BouncyCastleGpgSigner.canLocateSigningKey(BouncyCastleGpgSigner.java:97)
	at org.eclipse.egit.ui.internal.credentials.SignatureUtils.checkSigningKey(SignatureUtils.java:93)
	at org.eclipse.egit.ui.internal.dialogs.CreateTagDialog.createLeftSection(CreateTagDialog.java:607)
	at org.eclipse.egit.ui.internal.dialogs.CreateTagDialog.createDialogArea(CreateTagDialog.java:460)
	at org.eclipse.jface.dialogs.TitleAreaDialog.createContents(TitleAreaDialog.java:166)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.egit.ui.internal.dialogs.CreateTagDialog.create(CreateTagDialog.java:402)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.eclipse.egit.ui.internal.actions.TagActionHandler.execute(TagActionHandler.java:89)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.egit.ui.test.ContextMenuHelper$6.run(ContextMenuHelper.java:255)
	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable$5.doRun(UIThreadRunnable.java:224)
	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable$1.run(UIThreadRunnable.java:90)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4368)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3991)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.swtbot.eclipse.core.UITestApplication.runApp(UITestApplication.java:63)
	at org.eclipse.swtbot.eclipse.core.UITestApplication.start(UITestApplication.java:58)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.util.Iterable cannot be found by bcpg-jdk18on_1.78.0
	... 67 more
```

Looks like a bug in BC 1.78: the MANIFEST.MF of bcpg-jdk18on.jar looks broken; it has only java.* import-packages. So obviously with the OSGi classloader separation, org.bouncycastle.util.Iterable (which _is_ in bcprov-jdk18on, and which _is_ exported there) this Iterable class cannot be found when PGPObjectFactory is loaded.

**Comment by tomaswolf** [comment]
See also https://github.com/bcgit/bc-java/issues/1621 . :-(

**Comment by merks** [comment]
It looks like 1.78 is kind of broken 

https://github.com/apache/mina-sshd/commit/69b64dad16af3d11fab952879bd776e2e8716d47#commitcomment-140836201

Probably I need to exclude it from orbit and drop this PR.

**Comment by msohn** [comment]
we abandoned the EGit change updating to bc 1.78 and reverted the JGit change, 
see https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1192942 for the details

Open issue on bouncycastle for this: https://github.com/bcgit/bc-java/issues/1621

**Comment by merks** [comment]
I'll close this pull request and exclude this version from Orbit.

**Pull request closed without merging**
