### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iloveeclipse**
Added IBuilds job & download links

### CODE REVIEW

**Comment by iloveeclipse** [comment]
OK, that seem to be failing now because of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/181: 
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.jdt.feature.group 3.18.1400.qualifier
[ERROR]   Missing requirement: org.eclipse.jdt.feature.group 3.18.1400.qualifier requires 'org.eclipse.equinox.p2.iu; org.eclipse.jdt.compiler.apt 0.0.0' but it could not be found
[ERROR] 
[ERROR] See https://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.eclipse.jdt.feature:org.eclipse.jdt:3.18.1400-SNAPSHOT @ /home/jenkins/agent/workspace/.aggregator_iloveeclipse-patch-1/eclipse.jdt/org.eclipse.jdt-feature/pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

@akurtakov : where is "org.eclipse.jdt.feature" coming from?

**Comment by iloveeclipse** [comment]
> It would be best if you merge this repo in jdt.ui (or some other repo). If jdt committers don't know where things come there is desperate need for change.

See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/571

**Comment by iloveeclipse** [comment]
Alex, this change can be merged, or do you have objections?

**Comment by akurtakov** [comment]
Fine with me.

**Pull request merged**
