### PR TITLE
Version bump for 4.31 stream

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by akurtakov** [comment]
To be verified via https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1604 which uncovered it.

**Comment by HeikoKlare** [comment]
fyi: also done in #1563.

**Comment by akurtakov** [comment]
Sorry about that! I got in some "automated" mode trying to get verification builds working.

**Comment by HeikoKlare** [comment]
No problem. Just oned to mention that because builds for #1563 have already been executed, so might give insights before the verification of #1604 has finished.

**Pull request merged**
