### PR TITLE
Update icu4j to latest 72.1

### PR DESCRIPTION
**Pull request by merks**
https://repo1.maven.org/maven2/com/ibm/icu/icu4j/72.1/

### CODE REVIEW

**Comment by akurtakov** [comment]
Orbit not recognized looks like some database inconsistency which I hope @waynebeaton will take care of soon.
But ICU4J needs approval before we can push this one in.

**Comment by merks** [comment]
@akurtakov  Thank you for your responsiveness!

**Comment by waynebeaton** [comment]
@akurtakov You should be good-to-go.

**Comment by akurtakov** [comment]
@merks Would you like this one to go in RC1?

**Review by akurtakov — APPROVED** [review]

**Comment by waynebeaton** [comment]
> But ICU4J needs approval before we can push this one in.

FWIW, the rule is that you need approval before the content can be used in a _release_. The EF IP Policy does not prevent you from pushing a commit that references a library that has not yet been vetted.

**Comment by akurtakov** [comment]
I'm pushing this one for platform than.

**Pull request merged**
