### PR TITLE
Update to ECJ from M1

### PR DESCRIPTION
**Pull request by akurtakov**
Prep work for https://github.com/eclipse-platform/eclipse.platform.ui/pull/527 due to https://github.com/eclipse-jdt/eclipse.jdt.core/issues/585

### CODE REVIEW

**Comment by iloveeclipse** [comment]
@akurtakov : new I Build?

**Comment by akurtakov** [comment]
Already running.

**Comment by akurtakov** [comment]
https://ci.eclipse.org/releng/job/Builds/job/I-build-4.27/93

**Comment by iloveeclipse** [comment]
Great, thanks. Not that I expect we've really messed with compiler, but would be bad if we did but all the test code already uses Java 17 :-)

**Comment by akurtakov** [comment]
We used to have issue with lambda order causing comparator issues but IIRC this should be done now.

**Pull request merged**
