### PR TITLE
Update previous release version to 4.34 GA across build scripts

### PR DESCRIPTION
**Pull request by MohananRahul**
Fix https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2607

### CODE REVIEW

**Comment by MohananRahul** [comment]
Merging this PR as verification builds will not verify.

**Comment by HannesWell** [comment]
Isn't this applied too early? 4.34 is not yet released.
As far as I can tell, this currently breaks the I-build (even though it currently seems to be more severely broken at a infrastructure level).

**Comment by MohananRahul** [comment]
> Isn't this applied too early? 4.34 is not yet released. As far as I can tell, this currently breaks the I-build (even though it currently seems to be more severely broken at a infrastructure level).

The GA has already been promoted to SimRel, and it’s available—it's just not yet visible.

**Comment by HannesWell** [comment]
> > Isn't this applied too early? 4.34 is not yet released. As far as I can tell, this currently breaks the I-build (even though it currently seems to be more severely broken at a infrastructure level).
> 
> The GA has already been promoted to SimRel, and it’s available—it's just not yet visible.

Indeed. The actual problem was that one property was not updated accordingly in this change. Did it now in
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2612

**Pull request merged**
