### PR TITLE
Try some Jakarta OSGi artifacts from upstream Central

### PR DESCRIPTION
**Pull request by mickaelistria**
instead of Orbit

### CODE REVIEW

**Comment by HannesWell** [comment]
There is also https://repo1.maven.org/maven2/jakarta/inject/jakarta.inject-api/1.0.5/ to replace `javax.inject`.

**Comment by akurtakov** [comment]
What is the status of thisone?

**Comment by mickaelistria** [comment]
Let's do it step by step: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/753 adds the bundles and then we'll progressively try removing older ones.

**Comment by akurtakov** [comment]
Ping. Let's try to finish started work.

**Comment by mickaelistria** [comment]
Let's close in favor of #774 and similar ones.

**Pull request closed without merging**
