### PR TITLE
Add dependencies for PDE using Bnd Resolver

### PR DESCRIPTION
**Pull request by laeubi**

### CODE REVIEW

**Comment by laeubi** [comment]
@akurtakov as RC2 is done and no new builds are planned can we already merge this?

**Comment by akurtakov** [comment]
Let's wait till Monday as @MohananRahul mentioned he plans to work on opening the stream and try to not interfere with releng work so automation hopefully works and simplifies things from now on.

**Comment by merks** [comment]
That gives me a bit of time to figure (finally) out how to ease the Oomph setups through the awkward period when the next release begins before the current release is actually released.  I have some ideas and need to try them out.

**Comment by akurtakov** [comment]
Unrelated failure in verification build.

**Pull request merged**
