### PR TITLE
provide junit ScreenshotOnFailure TestWatcher

### PR DESCRIPTION
**Pull request by jukzi**

### CODE REVIEW

**Comment by HeikoKlare** [comment]
May this be better placed in [`org.eclipse.core.tests.harness`](https://github.com/eclipse-platform/eclipse.platform/tree/master/runtime/tests/org.eclipse.core.tests.harness), since it is not related to performance test?

**Comment by akurtakov** [comment]
> May this be better placed in [`org.eclipse.core.tests.harness`](https://github.com/eclipse-platform/eclipse.platform/tree/master/runtime/tests/org.eclipse.core.tests.harness), since it is not related to performance tests?

Probably even better place is https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/eclipse.platform.releng/bundles/org.eclipse.test .

**Review by akurtakov — CHANGES_REQUESTED** [review]
Please move to org.eclipse.test bundle.

**Comment by jukzi** [comment]
Moving it would be a hell of work. Moving the class would be an API breakage. TracingSuite requires it needs to be fixed, Access restrictions need to be fixed... . I don't like how it is either, but to clean up that mess seems too complicated :-(

**Comment by akurtakov** [comment]
Tests are not API incl org.eclipse.test. Does it make the task easier?

**Comment by jukzi** [comment]
technically they are API. Some tests just do not include org.eclipse.test but the performance one. so no it's not helpful.

**Comment by akurtakov** [comment]
Everything should be in o.e.test without any breakage so you can patch Screenshots in o.e.test bundle.

**Comment by akurtakov** [comment]
Tests in I-build seems to be in good shape now.

**Review by akurtakov — APPROVED** [review]
Looks good to me now.

**Comment by jukzi** [comment]
Not only seems that build error unrelated but should'nt it have produced an automated version bump @HannesWell ?
`org.eclipse.jdt.doc.user: Only qualifier changed for (org.eclipse.jdt.doc.user/3.15.2300.v20240927-0605). Expected to have bigger x.y.z than what is available in baseline (3.15.2300.v20240823-1014) -> [Help 1]`

**Comment by akurtakov** [comment]
It is caused by https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2392

**Comment by HannesWell** [comment]
> Not only seems that build error unrelated but should'nt it have produced an automated version bump @HannesWell ? `org.eclipse.jdt.doc.user: Only qualifier changed for (org.eclipse.jdt.doc.user/3.15.2300.v20240927-0605). Expected to have bigger x.y.z than what is available in baseline (3.15.2300.v20240823-1014) -> [Help 1]`

The version-increment workflow is not (yet) setup for this repository. In the current form it would be basically the same as the verification build. I plan to work on a Tycho mojo that should speed that up significantly but in the meantime I think it's not worth the effort to enable it in this repo.

**Pull request merged**
