### PR TITLE
Add asm-analysis to target

### PR DESCRIPTION
**Pull request by iloveeclipse**
See https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/364

### CODE REVIEW

**Comment by merks** [comment]
I notice issues related to this here:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/775#issue-1499746989

**Comment by iloveeclipse** [comment]
> I notice issues related to this here:

I've quickly scanned through the discussion, this PR shouldn't be wrong in the sense it will "fix" one broken thing and that "thing" will be **really** used by SDK.

Or did I understand that wrong?

**Review by akurtakov — APPROVED** [review]
This looks good. Please merge. Once merged it will take some time for jenkins jobs to run before jdt jenkins build can find it out.

**Comment by merks** [comment]
@iloveeclipse Yes, now you really use something that wasn't used and of course to use it all the requirements need to resolve so you are adding the "missing" thing.  Anyway, don't worry about it, I just wanted to link the issues...

**Comment by iloveeclipse** [comment]
OK thanks.

**Comment by iloveeclipse** [comment]
> This looks good. Please merge. Once merged it will take some time for jenkins jobs to run before jdt jenkins build can find it out.

How long it could take? A day? Or do we miss something else? 
Still not visible: https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/385

**Comment by akurtakov** [comment]
It takes 1-2 hours at most . asm-analysis is already in target environment as can be seen at https://repo.eclipse.org/content/repositories/eclipse/org/eclipse/eclipse-sdk-prereqs/4.27.0-SNAPSHOT/eclipse-sdk-prereqs-4.27.0-20230115.075136-1218.target so you're missing smth else.

**Pull request merged**
