### PR TITLE
Use org.glassfish:jakarta.el instead of org.glassfish:javax.el

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-platform/.github/issues/155

### CODE REVIEW

**Comment by merks** [comment]
@akurtakov 

I'm quite sure this is a drop-in replacement; it even has the same bundle symbolic name. 

I assume merging must wait until M1 is fully declared, right?

**Comment by akurtakov** [comment]
Yes, it's too late for M1

**Comment by akurtakov** [comment]
M1 announced. Merging.

**Comment by merks** [comment]
Thank you for following up. 👍

**Pull request merged**
