### PR TITLE
Add biz.aQute.repository to the target for usage by PDE

### PR DESCRIPTION
**Pull request by laeubi**
Contains some useful bnd-plugins to read repositories ... as I plan to enhance BND support in PDE this will be required then.

### CODE REVIEW

**Comment by laeubi** [comment]
@akurtakov as the new stream is now open I think we can merge this?

**Comment by akurtakov** [comment]
In general we waited for first I-build and formal announcement to the mailing list before merging other changes in. Not sure how will this go from now on with all the changes.

**Comment by laeubi** [comment]
Alright then I'll wait for the announcement.

**Comment by laeubi** [comment]
Build failure seems unrelated but something seems not configured correctly.

**Pull request merged**
