### PR TITLE
Update JUnit dependencies to 5.9.0

### LINKED ISSUE #442: Update JUnit to 5.9.0
Latest JUnit is 5.9.0 and Eclipse is using 5.8.1.

### PR DESCRIPTION
**Pull request by jjohnstn**
- fixes #442

### CODE REVIEW

**Comment by jjohnstn** [comment]
Note that I did a build of the SDK and then took that SDK and verified it could run the org.eclipse.jdt.ui.tests.  I also created a JUnit5 test and testsuite in a plug-in in the newly built SDK and verified they ran as expected.  JUnit 5.9.0 does add a restriction that @BeforeAll, etc.. methods must be public, but this is considered a fix.

**Comment by jjohnstn** [comment]
@akurtakov please note as you asked for this update

**Comment by iloveeclipse** [comment]
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: eclipse-junit-tests 4.25.0.qualifier
[ERROR]   Missing requirement: org.eclipse.test.feature.group 3.8.200.v20220730-0611 requires 'org.eclipse.equinox.p2.iu; junit-jupiter-api [5.8.1,5.8.1]' but it could not be found
[ERROR]   Cannot satisfy dependency: eclipse-junit-tests 4.25.0.qualifier depends on: org.eclipse.equinox.p2.iu; org.eclipse.test.feature.group 0.0.0

**Comment by akurtakov** [comment]
@iloveeclipse o.e.test.feature and probably others will have to be touched.

**Pull request merged**
