### PR TITLE
Replace jxpath by upstream one from Maven Central

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by mickaelistria** [comment]
This seems mostly good but would require a feature to be touched after the merge.
1 potential issue here is that we don't really move to a newer version, so it may be perceived as a version regression by the version comparison report.

**Comment by iloveeclipse** [comment]
This PR most likely caused SDK build failure:
https://ci.eclipse.org/releng/job/Builds/job/I-build-4.27/79/console
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:4.0.0-SNAPSHOT:assemble-repository (default-assemble-repository) on project eclipse.platform.repository: Could not assemble p2 repository: Mirroring failed: Messages while mirroring artifact descriptors.: [Failed to transfer artifact packed: osgi.bundle,org.jdom.source,1.1.1.v201101151400.: [Download of osgi.bundle,org.jdom.source,1.1.1.v201101151400 failed on repository file:/resolution-context-artifacts@%252Fhome%252Fjenkins%252Fagent%252Fworkspace%252FBuilds%252FI-build-4.27%252Feclipse.platform.releng.aggregator%252Feclipse.platform.releng.aggregator%252Fcje-production%252FgitCache%252Feclipse.platform.releng.aggregator%252Feclipse.platform.releng.tychoeclipsebuilder%252Feclipse.platform.repository. Retrying. : [Artifact packed: osgi.bundle,org.jdom.source,1.1.1.v201101151400 is not available in the repository file:/home/jenkins/agent/workspace/Builds/I-build-4.27/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/localMavenRepo/]; Artifact not found: packed: osgi.bundle,org.jdom.source,1.1.1.v201101151400.]]
```

@mickaelistria : Please check what is wrong with the change.

**Comment by iloveeclipse** [comment]
Note: my local build also fails, so it is not a file transfer issue, something must be wrong with the dependency itself.

**Comment by akurtakov** [comment]
I'm running local build to investigate till Mickael joins the party.

**Comment by iloveeclipse** [comment]
@mickaelistria , @akurtakov : any results? As said, my local build fails with same error.

**Comment by akurtakov** [comment]
I didn't manage to reproduce still :
* Full build fails with : (make-assembly) on project eclipse-junit-tests: Failed to create assembly: Error adding file to archive: /home/akurtakov/git/eclipse.platform.releng.aggregator/eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/../../eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/target/doc.bin.log -> [Help 1]
* eclipse.platform.repository build only - succeeds

**Comment by iloveeclipse** [comment]
I have that:
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:4.0.0-SNAPSHOT:assemble-repository (default-assemble-repository) on project eclipse.platform.repository: Could not assemble p2 repository: Mirroring failed: Messages while mirroring artifact descriptors.: [Failed to transfer artifact packed: osgi.bundle,org.jdom.source,1.1.1.v201101151400.: [Download of osgi.bundle,org.jdom.source,1.1.1.v201101151400 failed on repository file:/resolution-context-artifacts@%252Fdata%252F4x_platform%252Feclipse.platform.releng.aggregator%252Feclipse.platform.releng.tychoeclipsebuilder%252Feclipse.platform.repository. Retrying. : [Artifact packed: osgi.bundle,org.jdom.source,1.1.1.v201101151400 is not available in the repository file:/home/aloskuto/.m2/repository/]; Artifact not found: packed: osgi.bundle,org.jdom.source,1.1.1.v201101151400.]] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:4.0.0-SNAPSHOT:assemble-repository (default-assemble-repository) on project eclipse.platform.repository: Could not assemble p2 repository
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Could not assemble p2 repository
    at org.eclipse.tycho.plugins.p2.repository.AssembleRepositoryMojo.execute (AssembleRepositoryMojo.java:229)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.eclipse.tycho.p2.tools.FacadeException: Mirroring failed: Messages while mirroring artifact descriptors.: [Failed to transfer artifact packed: osgi.bundle,org.jdom.source,1.1.1.v201101151400.: [Download of osgi.bundle,org.jdom.source,1.1.1.v201101151400 failed on repository file:/resolution-context-artifacts@%252Fdata%252F4x_platform%252Feclipse.platform.releng.aggregator%252Feclipse.platform.releng.tychoeclipsebuilder%252Feclipse.platform.repository. Retrying. : [Artifact packed: osgi.bundle,org.jdom.source,1.1.1.v201101151400 is not available in the repository file:/home/aloskuto/.m2/repository/]; Artifact not found: packed: osgi.bundle,org.jdom.source,1.1.1.v201101151400.]]
    at org.eclipse.tycho.p2tools.MirrorApplicationServiceImpl.checkStatus (MirrorApplicationServiceImpl.java:318)
    at org.eclipse.tycho.p2tools.MirrorApplicationServiceImpl.mirrorReactor (MirrorApplicationServiceImpl.java:183)
    at org.eclipse.tycho.plugins.p2.repository.AssembleRepositoryMojo.execute (AssembleRepositoryMojo.java:225)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
```

**Comment by iloveeclipse** [comment]
May be I'm looking wrong, but I can't find org.jdom **v1** at all in **recent** Orbit builds.

I see the build uses https://download.eclipse.org/tools/orbit/downloads/drops/R20201118194144/
The bundle **seem to be there**: 
- https://download.eclipse.org/tools/orbit/downloads/drops/R20201118194144/repository/plugins/
- https://download.eclipse.org/tools/orbit/downloads/drops/R20201118194144/repository/plugins/org.jdom.source_1.1.1.v201101151400.jar

Looking at maven warnings **right before** the actual error I see the jar **was** downloaded but:
```
[WARNING] [f846bbdb-7960-47d4-af89-d03a3df1c208][extension>org.eclipse.tycho:tycho-maven-plugin:4.0.0-SNAPSHOT] The digest algorithms (md5) used to verify osgi.bundle,org.jdom.source,1.1.1.v201101151400 have severely compromised security. Please report this concern to the artifact provider.
[WARNING] [f846bbdb-7960-47d4-af89-d03a3df1c208][extension>org.eclipse.tycho:tycho-maven-plugin:4.0.0-SNAPSHOT] The digest algorithms (md5) used to verify osgi.bundle,org.jdom.source,1.1.1.v201101151400 have severely compromised security. Please report this concern to the artifact provider.
[INFO] Downloading from p2: https://download.eclipse.org/tools/orbit/downloads/drops/R20201118194144/repository/plugins/org.jdom.source_1.1.1.v201101151400.jar
[INFO] Downloaded from p2: https://download.eclipse.org/tools/orbit/downloads/drops/R20201118194144/repository/plugins/org.jdom.source_1.1.1.v201101151400.jar (266 KB at 330 KB/s)
[WARNING] [f846bbdb-7960-47d4-af89-d03a3df1c208][extension>org.eclipse.tycho:tycho-maven-plugin:4.0.0-SNAPSHOT] The digest algorithms (md5) used to verify osgi.bundle,org.jdom.source,1.1.1.v201101151400 have severely compromised security. Please report this concern to the artifact provider.
[WARNING] Mirror tool: Messages while mirroring artifact descriptors.: [Failed to transfer artifact packed: osgi.bundle,org.jdom.source,1.1.1.v201101151400.: [Download of osgi.bundle,org.jdom.source,1.1.1.v201101151400 failed on repository file:/resolution-context-artifacts@%252Fdata%252F4x_platform%252Feclipse.platform.releng.aggregator%252Feclipse.platform.releng.tychoeclipsebuilder%252Feclipse.platform.repository. Retrying. : [Artifact packed: osgi.bundle,org.jdom.source,1.1.1.v201101151400 is not available in the repository file:/home/aloskuto/.m2/repository/]; Artifact not found: packed: osgi.bundle,org.jdom.source,1.1.1.v201101151400.]]
```

So it this security issue the actual problem why the jar is "not found"?

**Comment by akurtakov** [comment]
It has been removed from recent orbit as it was build from old cvs sources and no one cared to migrate it. IMHO it's time to just get rid of  org.eclipse.e4.emf.xpath . It's not used by anything else and jxpath has 6 CVEs against it with 5 more coming from its dependencies and dead upstream (last release was 15 years ago).

**Comment by akurtakov** [comment]
Only code usage is https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.e4.ui.model.workbench/src/org/eclipse/e4/ui/model/fragment/impl/StringModelFragmentImpl.java#L356 .
@merks Could you take a look and tell us whether EMF provides similar functionality without depending on e4.emf.xpath bundle?

**Comment by akurtakov** [comment]
I have to leave early today so I'm leaving this to @mickaelistria .

**Comment by mickaelistria** [comment]
Getting rid of jxpath was already discussed and is not easily actionable right now.
I cannot reproduce it either at the moment.
@iloveeclipse can you please try, from eclipse.platform.releng.aggregator/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository the command `mvn clean verify -Pbuild-individual-bundles` ?
One thing that I notice seems incorrect in the error message you share is that it looks like the "packed" artifact is required; but that shouldn't be the case. I'm not even sure that p2 can still consume packed artifacts these days.

**Comment by iloveeclipse** [comment]
This command works. SDK build doesn't.

**Comment by mickaelistria** [comment]
> This command works. SDK build doesn't.

OK thanks. I now understand why this command works as expected: it's still using the older jxpath which doesn't require jdom.
I'll try tp build a minimal reproducer and will then debug.

**Comment by iloveeclipse** [comment]
@mickaelistria : if the fix takes longer, would be good to revert this PR today so we can have SDK builds running over weekend. Usually if the builds are broken, everyone starts to push broken PR's too :-(
WDYT?

**Comment by merks** [comment]
With m2 next week, it's probably important to ensure a good level of stability.

**Comment by mickaelistria** [comment]
I've only made some progress at reproducing it, and even those are not very satisfactory yet (seems like it only fails from a clean repo). I suspect the issue is in Tycho and not something we can fix in Platform shortly.
Feel free to revert in the meantime.

**Comment by iloveeclipse** [comment]
OK, see https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/813

**Comment by mickaelistria** [comment]
> I assume because there was a second commit in another repo, which I've overlooked: https://github.com/eclipse-platform/eclipse.platform.ui/pull/519

I don't think this commit cause issue, on the contrary.

**Comment by iloveeclipse** [comment]
> I don't think this commit cause issue, on the contrary.

OK, what causes the SDK build failure now, after reverting first commit?

**Comment by mickaelistria** [comment]
> OK, what causes the SDK build failure now, after reverting first commit?

I suspect a bug in Tycho, which will affect the first artifact it's trying to fetch from this Orbit repo.

**Comment by iloveeclipse** [comment]
> I suspect a bug in Tycho, which will affect the first artifact it's trying to fetch from this Orbit repo.

@laeubi : can we please revert whatever was done in related area in tycho in last day? 
We would like to have some successful SDK builds before M2.

**Comment by iloveeclipse** [comment]
@mickaelistria : let's try the second revert - it can't be worse as now.
If that is still failing, we know it's tycho.

**Comment by laeubi** [comment]
I see many times "packed" artifacts in the error, pack200 is not supported anymore for a long time, so its either an old Tycho version or something still requesting "old" stuff...

If one can give me a hint how to reproduce, or even better provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue, I can take a look.

Reverting random stuff is defiantly not an option for Tycho, all of Tychos testcases pass as well as the platform verification builds, so there is no regression in Tycho unless someone proves otherwise with a failing test-case.

**Comment by iloveeclipse** [comment]
I've triggered build with second revert now: https://ci.eclipse.org/releng/job/Builds/job/I-build-4.27/82/

If this fails too, @laeubi would be great if you could compare tycho versions and differences between tycho used in 
https://ci.eclipse.org/releng/job/Builds/job/I-build-4.27/78/ (last good SDK build) and https://ci.eclipse.org/releng/job/Builds/job/I-build-4.27/79/ (first failing with strange jxpath errors).

**Comment by laeubi** [comment]
Whatever is causing this we need an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue, so it can't happen again ... I'll try to get an idea here but if someone will be able to help with a reproducer it would be great.

**Comment by mickaelistria** [comment]
See https://github.com/eclipse-tycho/tycho/issues/2009

**Pull request merged**
