### PR TITLE
[Build] Send Y-build results to jdt-dev mailing-list

### PR DESCRIPTION
**Pull request by HannesWell**
instead of to a fixed lists of interested people.
As people and their interest may come and go it's simpler to not have a fixed list of people to which notifications are send.

@jarthana, @mpalat or @stephan-herrmann, what do you think?

### CODE REVIEW

**Comment by akurtakov** [comment]
Totally makes sense to me. As I have been receiving this email, I always thought it's coming through jdt-dev now I see I was listed explicitly.

**Comment by jarthana** [comment]
I am OK with it. The question is, will there be anyone in the mailing list that would think they are being spammed?

**Comment by mpalat** [comment]
Hi Folks, I don't see any mail to jdt-dev - assuming it is so because of no successful Y build post 23rd december - will raise an issue

**Comment by mpalat** [comment]
Is it because jdt-dev requires subscription, like other mailing list and this email id is not recognized?

**Comment by HannesWell** [comment]
> Is it because jdt-dev requires subscription, like other mailing list and this email id [[genie.releng@eclipse.org](mailto:genie.releng@eclipse.org)?] is not recognized?

Good point, that's probably the cause. Asked the infra-team to subscribe the bot:
- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5481

**Comment by HannesWell** [comment]
> > Is it because jdt-dev requires subscription, like other mailing list and this email id [[genie.releng@eclipse.org](mailto:genie.releng@eclipse.org)?] is not recognized?
> 
> Good point, that's probably the cause. Asked the infra-team to subscribe the bot:
> 
>     * https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5481

For the latest Y-build I received a notification, so I think this finally works as expected.

**Pull request merged**
