### PR TITLE
Update mockito-core to 5.7.0

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
@iloveeclipse 

This failure appears to be unrelated to my change.

> 12:01:03  [ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.4-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.jdt.apt.pluggable.core: Only qualifier changed for (org.eclipse.jdt.apt.pluggable.core/1.4.100.v20231103-0801). Expected to have bigger x.y.z than what is 

Is this a known problem that will maybe shortly no longer be a problem?

**Comment by iloveeclipse** [comment]
> Is this a known problem that will maybe shortly no longer be a problem?

Never heard about this one. Most likely recent regression.

**Comment by iloveeclipse** [comment]
> Of what? This just indicates that org.eclipse.jdt.apt.pluggable.core has recent changes but was not version bumped (not sure if there is a recent ECJ change somewhere).

Yes, that was what I've meant. It is a build regression due the recent change.

@jukzi : please check & update versions for bundles that need a version bump.
This is regression from https://github.com/eclipse-jdt/eclipse.jdt.core/commit/23f552fd89de7dce7c1b992b36035099660c564f

**Comment by akurtakov** [comment]
The issue comes from JDT core build not doing baseline comparison in its verification build like the rest thus such things go on unnoticed. Line like https://github.com/eclipse-platform/eclipse.platform.ui/blob/728f0760e1fb1b641ebe2ffa5c275a23e5762d58/Jenkinsfile#L21 should be added to jdt.core jenkinsfile.

**Comment by iloveeclipse** [comment]
> The issue comes from JDT core build not doing baseline comparison in its verification build like the rest thus such things go on unnoticed. Line like https://github.com/eclipse-platform/eclipse.platform.ui/blob/728f0760e1fb1b641ebe2ffa5c275a23e5762d58/Jenkinsfile#L21 should be added to jdt.core jenkinsfile.

@akurtakov : could you please create PR with the proposed change, or is there any specific reason why JDT doesn't check versions?

**Comment by akurtakov** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1554

**Pull request merged**
