### PR TITLE
Update commons-fileupload to 1.5

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
@akurtakov 

I assume we want this one too.  I expect /org.eclipse.sdk.tests (feature)/forceQualifierUpdate.txt will need a bump.

**Comment by akurtakov** [comment]
Yes, please. Once we go in RC phase we will have to slow down.

**Comment by merks** [comment]
@akurtakov 

I'm a bit concerned that the build passed but I expected this include to be a problem:

image

Should I bump that one's qualifier just to be safe?

I see https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/7109 is taking a bit longer than usual...

**Comment by akurtakov** [comment]
If the build succeeds let's trust it and don't touch needlessly. If smth else in this feature has been touched it would happen to be a "touch"

**Comment by merks** [comment]
@akurtakov Okay.  Should I wait for the IP review to finish?  It seems some manual process has kicked in.  Though I believe we are allowed to do the review in parallel.  It's your call...

**Comment by akurtakov** [comment]
Yes, we have to wait for the IP process as we can not release until approved and I'm not looking for a revert in RC phases if this happens to not be approved for some reason.

**Comment by akurtakov** [comment]
Overall, in Platform we play it safe and include things only after approved as the convoluted build is not making revert fun.

**Comment by merks** [comment]
@akurtakov 

Thanks so much, as always, for your ultra-speedy responses!  😃

**Pull request merged**
