### PR TITLE
2nd attempt to touch org.eclipse.help

### PR DESCRIPTION
**Pull request by iloveeclipse**
Needed to "include" latest org.eclipse.equinox.http.jetty, second try...

Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1419

### CODE REVIEW

**Comment by akurtakov** [comment]
These touches will not help. Jetty 12.0.2 is due tomorrow and the problem should be fixed by such an update as already explained in the issue.

**Comment by iloveeclipse** [comment]
> the problem should be fixed by such an update as already explained in the issue.

I don't think it is same issue, but we can wait if jetty update helps.

**Comment by akurtakov** [comment]
Is this one still needed?

**Comment by iloveeclipse** [comment]
> Is this one still needed?

Nope.

**Pull request closed without merging**
