### PR TITLE
Documenting https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1716

### PR DESCRIPTION
**Pull request by stephan-herrmann**
Documenting https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1716 (ecj supports annotation `@Owning` for static analysis of resource closing).

See also https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1059

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
> Such content would also be helpful here: ...

Thanks, yes I'll have a look.

May I first ask your help to get this doc-only change merged for RC2?

I validated the html file using https://validator.w3.org so even waiting for the build (full SDK build?) seems unnecessary.

PS: In former times I had commit rights for such documentation, but apparently I lost this during one of the repository moves.

**Comment by akurtakov** [comment]
You lost commit rights during the Gerrit to GH move as since then only committers to given project can have push rights to it (no exceptions/shared repos/etc. as we have been told by EF anymore).
Anyway, latest status of releng improved to the state where we can be confident that moving *all* jdt doc bundles to https://github.com/eclipse-jdt/eclipse.jdt should fix that so JDT project and committers are responsible for JDT documentation bundles. I'll try to find time to drive that during 4.32 development.

**Comment by stephan-herrmann** [comment]
> https://eclipse.dev/eclipse/news/4.31/jdt.php
> https://github.com/eclipse-platform/www.eclipse.org-eclipse/blob/master/news/4.31/jdt.html

Frankly I'm now confused about that redundancy. Which page should one be changing and in case of the php page: how? They don't seem to be well in sync, are they?

**Comment by merks** [comment]
This page is just a tiny wrapper:

https://github.com/eclipse-platform/www.eclipse.org-eclipse/blob/master/news/4.31/jdt.php

The page you edit can be viewed directly on the website too:

https://eclipse.dev/eclipse/news/4.31/jdt.html

I have to step away from the computer for a while

@akurtakov 

I think it's good and fine to get doc changes in right now...

**Comment by akurtakov** [comment]
It's last minute for doc changes. I unfortunately can't dedicate the time to look into it so I can just push on behalf of @stephan-herrmann if/when he says so.

**Comment by stephan-herrmann** [comment]
Or should I even copy new content from https://github.com/eclipse-platform/www.eclipse.org-eclipse/blob/master/news/4.31/jdt.html over into this file?

**Comment by laeubi** [comment]
I would have assumed content should go here:
https://github.com/eclipse-platform/www.eclipse.org-eclipse/blob/master/news/4.31/jdt.html

**Comment by stephan-herrmann** [comment]
> It's last minute for doc changes.

I know, and I'm sorry about that,  but apparently org.eclipse.jdt.doc.user is not even in a state ready to ship 4.31.

**Comment by akurtakov** [comment]
So I see @alshamams did a commit https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/63c702f2fb67f9237ec275a7d58481344a13bb05 for 4.30 putting everything from https://github.com/eclipse-platform/www.eclipse.org-eclipse/blob/master/news/4.30 into the doc bundles. So I have to defer the question when such action is planned for 4.31 to the one that did it last time.
I would be very thankful to everyone if he/she tries to get things saner as all those manual edits/copies would better not be done at all.

**Comment by akurtakov** [comment]
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1814 lists "New & Noteworthy" which I assume is this coping of content.

**Comment by alshamams** [comment]
Hi @akurtakov ,
I am currently working on copying the eclipse news repo content over to the platform repo. Will complete N and N soon.

**Comment by akurtakov** [comment]
What is the status of this one? I guess it should be closed but doublechecking.

**Comment by stephan-herrmann** [comment]
> What is the status of this one? I guess it should be closed but doublechecking.

#1838 did introduce a couple of glitches, but those didn't justify a last second re-spin, so yes, this is resolved as best as we could at this late point in time. 

Hint for next time: it would be nice if there was some time window, where contributors can realistically verify that "their" content is adopted correctly in the corresponding doc bundle.

**Comment by merks** [comment]
@MohananRahul 

Yes, I did a bunch of N&N changes on the weekend before the final build, e.g.,

https://github.com/eclipse-platform/www.eclipse.org-eclipse/commit/bac7e3ba49ab6ba2e9ffec6d0fbdc2ca82e8b968

I did that because I know from the release before that the stuff got copied which I didn't know about nor expect.

**Pull request closed without merging**
