### PR TITLE
Update the target platform for Orbit m2

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1199

### CODE REVIEW

**Comment by merks** [comment]
@iloveeclipse 

I'm ready to merge this now, but I noticed that the verification build here does not actually run any tests.  That concerns me a bit because of the changes to org.junit.   When I merge this, I want to immediately start a nightly integration build.  Could you please help me with that?  I.e., could you squash and merge this, start a build, and post a link to the build here please?

**Comment by laeubi** [comment]
@merks if you want the test to run (but keep in mind this can take long) you need to remove (temporary maybe with another PR) the `-DskipTests` flag from the Jenkinsfile.

**Comment by merks** [comment]
@laeubi   

That's a good idea!  Thanks!!

@iloveeclipse 

I shall try that first!

**Comment by merks** [comment]
@laeubi 

I see the tests are running now, so your idea was a good one!   So far I see nothing failing that suggest target platform changes are bad...

**Comment by merks** [comment]
Well, a bunch of tests ran but I don't think everything is well configured to run tests when it fails like this eventually:
```
11:14:38  [INFO] Command line:
11:14:38  	[/opt/tools/java/openjdk/jdk-17/latest/bin/java, -Dosgi.noShutdown=false, -Dosgi.os=linux, -Dosgi.ws=gtk, -Dosgi.arch=x86_64, -Xmx1G, -Djdt.default.test.compliance=1.8, -DDetectVMInstallationsJob.disabled=true, ${tycho.surefire.argLine}, -Dosgi.clean=true, -ea, -jar, /home/jenkins/agent/workspace/atform.releng.aggregator_PR-1233/equinox/bundles/org.eclipse.equinox.launcher/target/org.eclipse.equinox.launcher-1.6.500-SNAPSHOT.jar, -data, /home/jenkins/agent/workspace/atform.releng.aggregator_PR-1233/eclipse.jdt.core/org.eclipse.jdt.core.tests.model/target/work/data, -install, /home/jenkins/agent/workspace/atform.releng.aggregator_PR-1233/eclipse.jdt.core/org.eclipse.jdt.core.tests.model/target/work, -configuration, /home/jenkins/agent/workspace/atform.releng.aggregator_PR-1233/eclipse.jdt.core/org.eclipse.jdt.core.tests.model/target/work/configuration, -application, org.eclipse.tycho.surefire.osgibooter.headlesstest, -testproperties, /home/jenkins/agent/workspace/atform.releng.aggregator_PR-1233/eclipse.jdt.core/org.eclipse.jdt.core.tests.model/target/surefire.properties]
11:14:38  Error: Could not find or load main class ${tycho.surefire.argLine}
11:14:38  Caused by: java.lang.ClassNotFoundException: ${tycho.surefire.argLine}
```
This is not related to target platform content.

I will revert the changes to run tests and assume all is good...

**Comment by merks** [comment]
@iloveeclipse 

It would probably be good to kick off a nightly build...

**Comment by iloveeclipse** [comment]
https://ci.eclipse.org/releng/job/Builds/job/I-build-4.29/75/

**Comment by HeikoKlare** [comment]
The Lucene version update makes the according index compatility test in platform fail in current builds such as https://ci.eclipse.org/platform/job/eclipse.platform/job/PR-579/4/testReport/

Is it a proper way to simply adapt the compatibility test case? https://github.com/eclipse-platform/eclipse.platform/pull/595

**Comment by merks** [comment]
@HeikoKlare 

It might be proper to delete the test rather than update it each time Lucene updates simply to match the Lucene version yet again.  I.e., I think the point was to be sure that we pre-index using the same version of Lucene as we have in the target platform, but I don't think we do that at all anymore.

**Pull request merged**
