### PR TITLE
Update to jetty 10.0.15

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
@akurtakov 

It's odd that this would fail for Jetty, an Eclipse project!

/request-license-review

**Comment by merks** [comment]
I don't see that the review is started either with no new issues here:

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/

**Comment by HannesWell** [comment]
> I don't see that the review is started either with no new issues here:
> 
> https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/

The string `/request-license-review` has to be the only content of the comment.

I changed the license-vetting workflow to automatically request reviews for unvetted licenses if dependabot creates the PR, but @laeubi reported that this is not yet working and from my analysis so far the reason is that the gitlab-api token cannot be read by non committers.
Nevertheless I could extend the workflow so that for PRs created by committers the requests are created automatically as well, if the license is not vetted.

**Comment by HannesWell** [comment]
> It's odd that this would fail for Jetty, an Eclipse project!

It failed for many more projects that are even eclipse-platform projects (and tests?).
@waynebeaton I believe something is flaky here.

**Comment by waynebeaton** [comment]
It's not the code that's flaky...

It turns out that identifying the Eclipse project from the ID in the general case is relatively hard. I've recently been tweaking the routine that sorts this out to improve the quality of the results; but there's been a small number of regressions.

I think that I've got this sorted out. Try it again, please.

**Comment by HannesWell** [comment]
Thanks Wayne.

> I think that I've got this sorted out. Try it again, please.

There are much less missing artifacts but still four that cannot be verified.

```
[INFO] --- license-tool-plugin:0.0.1-SNAPSHOT:license-check (default-cli) @ platform-aggregator ---
[INFO] Querying Eclipse Foundation for license data for 418 items.
[INFO] Found 414 items.
[INFO] Querying ClearlyDefined for license data for 4 items.
[INFO] Found 4 items.
[INFO] License information could not be automatically verified for the following content:
[INFO] 
[INFO] maven/mavencentral/eclipse.platform.ua/org.eclipse.tips.core/0.3.0-SNAPSHOT
[INFO] maven/mavencentral/eclipse.platform.ua/org.eclipse.tips.ide/0.3.0-SNAPSHOT
[INFO] maven/mavencentral/eclipse.platform.ua/org.eclipse.tips.json/0.3.0-SNAPSHOT
[INFO] maven/mavencentral/eclipse.platform.ua/org.eclipse.tips.ui/0.3.0-SNAPSHOT
[INFO] 
[INFO] This content is either not correctly mapped by the system, or requires review.
```

**Comment by waynebeaton** [comment]
> There are much less missing artifacts but still four that cannot be verified.

Oops. Fixed more.

**Pull request merged**
