### PR TITLE
[I-Build-Tests] Use JDK23-EA for Linux-Java23 tests

### PR DESCRIPTION
**Pull request by HannesWell**
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1664

See also https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5179

### CODE REVIEW

**Comment by HannesWell** [comment]
The verification build does not test this, but I tested it in my local Jenkins by replying the existing job with the changes applied and I'm to test this instead.

**Comment by jukzi** [comment]
jdt.ui tests still fail. To fix we need a jdk after 2024-10-27 .
```
[echoproperties] java.vendor.version=Temurin-23+37-202410121216
[echoproperties] java.version=23.0.1-beta
[echoproperties] java.version.date=2024-10-15
```
https://download.eclipse.org/eclipse/downloads/drops4/I20241107-0510/testresults/consolelogs/ep434I-unit-linux-x86_64-java23_linux.gtk.x86_64_23_consolelog.txt

**Comment by HannesWell** [comment]
It's a bit confusing when looking at https://adoptium.net/de/temurin/nightly/?version=23,
there are some builds from 4. November 2024, but they have tagged with `23.0.1-beta+11-202411021221` and I assume 
`23.0.1-beta+11` is older than `23+37` ?
But I'm not sure what is right and what's wrong here.

In general if anybody can provide me a link to a better JDK it can be changed easily.
At the moment we use
https://staging-api.adoptium.net/v3/binary/latest/23/ea/linux/x64/jdk/hotspot/normal/eclipse?project=jdk
This should download the latest early access build of JDK 23?

**Comment by akurtakov** [comment]
I believe 23+37 means build 37 of stream 23.0.0, while 23.0.1-beta+11 means build 11 of stream 23.0.1 - aka the later is newer as it's beta builds towards 23.0.1.

**Comment by HannesWell** [comment]
I now wanted to try out
https://github.com/adoptium/temurin23-binaries/releases/download/jdk23u-2024-11-04-10-15-beta/OpenJDK23U-jdk_x64_linux_hotspot_2024-11-04-10-15.tar.gz

But in the latest I-builds the JDT failures for java-23 seem to be gone.
@jukzi do you know if a fix has been applied in JDT?

**Comment by jukzi** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1789

**Comment by HannesWell** [comment]
> [eclipse-jdt/eclipse.jdt.ui#1789](https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1789)

That makes it impossible to test if another JDK build contains the fix :/

**Pull request merged**
