### PR TITLE
add Java 20 test

### PR DESCRIPTION
**Pull request by SDawley**
Adding a Java 20 unit tests so we can get an idea of what's coming.

### CODE REVIEW

**Comment by iloveeclipse** [comment]
@SDawley : not sure if that is the reason for **no tests executed** today?
https://download.eclipse.org/eclipse/downloads/drops4/I20221025-1800/

**Comment by iloveeclipse** [comment]
Last tests were triggered 1 day ago, according to https://ci.eclipse.org/releng/view/Automated%20tests/

**Comment by akurtakov** [comment]
This doesn't look like an issue as it's just the groovy file but it isn't hooked in the build yet. From https://ci.eclipse.org/releng/job/Builds/job/I-build-4.26/66/console :
```
[Pipeline] { (Trigger tests)
[Pipeline] build (Building Automated Tests » ep426I-unit-cen64-gtk3-java11)
19:48:06  Scheduling project: [Automated Tests » ep426I-unit-cen64-gtk3-java11](https://ci.eclipse.org/releng/job/AutomatedTests/job/ep426I-unit-cen64-gtk3-java11/)
[Pipeline] build (Building Automated Tests » ep426I-unit-cen64-gtk3-java17)
19:48:06  Scheduling project: [Automated Tests » ep426I-unit-cen64-gtk3-java17](https://ci.eclipse.org/releng/job/AutomatedTests/job/ep426I-unit-cen64-gtk3-java17/)
[Pipeline] build (Building Automated Tests » ep426I-unit-cen64-gtk3-java19)
19:48:06  Scheduling project: [Automated Tests » ep426I-unit-cen64-gtk3-java19](https://ci.eclipse.org/releng/job/AutomatedTests/job/ep426I-unit-cen64-gtk3-java19/)
[Pipeline] build (Building Automated Tests » ep426I-unit-macM1-java17)
19:48:06  Scheduling project: [Automated Tests » ep426I-unit-macM1-java17](https://ci.eclipse.org/releng/job/AutomatedTests/job/ep426I-unit-macM1-java17/)
[Pipeline] build (Building Automated Tests » ep426I-unit-mac64-java17)
19:48:06  Scheduling project: [Automated Tests » ep426I-unit-mac64-java17](https://ci.eclipse.org/releng/job/AutomatedTests/job/ep426I-unit-mac64-java17/)
[Pipeline] build (Building Automated Tests » ep426I-unit-win32-java11)
19:48:06  Scheduling project: [Automated Tests » ep426I-unit-win32-java11](https://ci.eclipse.org/releng/job/AutomatedTests/job/ep426I-unit-win32-java11/)
[Pipeline] build (Building ep426I-perf-lin64-baseline)
19:48:06  Scheduling project: [ep426I-perf-lin64-baseline](https://ci.eclipse.org/releng/job/ep426I-perf-lin64-baseline/)
[Pipeline] build (Building Start-smoke-tests)
19:48:06  Scheduling project: [Start-smoke-tests](https://ci.eclipse.org/releng/job/Start-smoke-tests/)

```

**Comment by iloveeclipse** [comment]
Yes, the build is there, but it looks like collect results job failed, or at least I don't see it being executed for few days:
https://ci.eclipse.org/releng/job/Releng/job/ep-collectResults/

I guess I can manually trigger that?

**Comment by akurtakov** [comment]
Yes, you only have to figure all the parameters right.

**Comment by iloveeclipse** [comment]
> Yes, you only have to figure all the parameters right.

Do **you** know which parameters are right? Build ID `I20221025-1800`?

**Comment by iloveeclipse** [comment]
I've tried with I20221025-1800. Let see...

**Comment by akurtakov** [comment]
So it looks like this one is the "new" job where @SDawley tries to get things to one level of magic less. https://ci.eclipse.org/releng/job/ep-collectResults/17368/ should be the old one that's supposed to still be in used. 
@SDawley , please clarify what is going on here.

**Comment by sravanlakkimsetti** [comment]
Understood the problem. Give me sometime to fix. 

There are two jobs here 
New one: https://ci.eclipse.org/releng/job/Releng/job/ep-collectResults/
Old one: https://ci.eclipse.org/releng/view/Automated%20tests/job/ep-collectResults/

New job has jdt to be used set as  "Default" switching this to "openjdk-jdk17-latest" fixes the problem

There is another problem because of job structure change.
Previously we used to access the test run results archive using https://ci.eclipse.org/releng/job/ep426I-unit-cen64-gtk3-java11/lastSuccessfulBuild/artifact/ Now this has to be accessed using https://ci.eclipse.org/releng/job/AutomatedTests/job/ep426I-unit-cen64-gtk3-java11/lastSuccessfulBuild/artifact/

Will provide a patch shortly

**Comment by akurtakov** [comment]
Thanks @sravanlakkimsetti ! I can't wait for the day when everything is in Jenkins so we can see/revert changes easilty when things break.

**Comment by sravanlakkimsetti** [comment]
Success. Fixed with https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/647

**Comment by iloveeclipse** [comment]
> Success. Fixed with #647

Thanks Sravan!

**Comment by SDawley** [comment]
Thank you!

**Pull request merged**
