### PR TITLE
Use Tycho 4.0.5 SNAPSHOT

### PR DESCRIPTION
**Pull request by laeubi**
As tycho 4.0.5 contains some important Api Tools fixes we should use the snapshot until the release.

**This should be merged as soon as master is opened for next development cycle.**

### CODE REVIEW

**Comment by laeubi** [comment]
@akurtakov should we merge this now?

**Comment by laeubi** [comment]
@akurtakov seems like missing version bumps for JDT?!? Can/should we merge anyways?

**Comment by akurtakov** [comment]
I am fixing JDT right now and would rather not push things with failing verification unless absolutely needed. 
Feel free to open PRs for JDT in cases like that next time :).

**Comment by akurtakov** [comment]
The failure now is:
```
[WARNING] The artifact org.eclipse.tycho.extras:tycho-eclipserun-plugin:jar:4.0.5-20231128.144538-18 has been relocated to org.eclipse.tycho:tycho-eclipse-plugin:jar:4.0.5-20231128.144538-18: The eclipse-run mojo is now part of the tycho-eclipse-plugin
11:32:57  [WARNING] The POM for org.eclipse.tycho:tycho-eclipse-plugin:jar:4.0.5-20231128.144538-18 is missing, no dependency information available
11:32:57  [WARNING] The artifact org.eclipse.tycho.extras:tycho-eclipserun-plugin:jar:4.0.5-20231128.144538-18 has been relocated to org.eclipse.tycho:tycho-eclipse-plugin:jar:4.0.5-20231128.144538-18: The eclipse-run mojo is now part of the tycho-eclipse-plugin
11:32:57  [ERROR] Plugin org.eclipse.tycho.extras:tycho-eclipserun-plugin:4.0.5-SNAPSHOT or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.eclipse.tycho:tycho-eclipse-plugin:jar:4.0.5-20231128.144538-18 (absent): org.eclipse.tycho:tycho-eclipse-plugin:jar:4.0.5-20231128.144538-18 was not found in https://repo.eclipse.org/content/repositories/tycho-snapshots/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of tycho-snapshots has elapsed or updates are forced -> [Help 1]
```

**Comment by laeubi** [comment]
I forced update now what now shows some projects still using old parent pom...

**Comment by akurtakov** [comment]
You rebased on old commit for some reason.

**Comment by laeubi** [comment]
I have no clue why it complains about not finding the plugin it is obviously here:

https://repo.eclipse.org/content/repositories/tycho-snapshots/org/eclipse/tycho/tycho-eclipse-plugin/4.0.5-SNAPSHOT/

**Comment by akurtakov** [comment]
Could it be the usage of tycho-eclipserun-plugin for which there is relocation?

**Comment by laeubi** [comment]
> Could it be the usage of tycho-eclipserun-plugin for which there is relocation?

The point of relocation is that "it works" without a change will see if I can get some support from the maven devs...

**Comment by laeubi** [comment]
Lets see if that helps:
- https://github.com/eclipse-tycho/tycho/pull/3098

**Pull request merged**
