### PR TITLE
Update net.bytebuddy and org.mockito to the latest version

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
@akurtakov This is another generated update to the available versions.  Any concerns?

**Comment by akurtakov** [comment]
If license check is fine it should be fine.

**Comment by merks** [comment]
Apparently the license checker doesn't like it.

**Comment by akurtakov** [comment]
@merks as you can see from previous comments there is some nice automation to auto open iplab issues. Use it in the future.

**Comment by akurtakov** [comment]
Lucene is approved already for inclusion in Orbit so this is just iplab database issue. Failing build should no longer happen due to https://github.com/eclipse-platform/eclipse.platform.releng/commit/38a6546e18d6f3adcb37706a6e1d3f5787c54663 .

**Pull request merged**
