### PR TITLE
Update ICU4J to version 71.1

### PR DESCRIPTION
**Pull request by akurtakov**
This version updates CLDR to 41 and adds Unicode 14 support.

### CODE REVIEW

**Comment by HannesWell** [comment]
> /request-license-review

Glad to see that the simplified license review requests finally work completely. :)

**Comment by iloveeclipse** [comment]
This caused "comparator issues" in JDT, see
https://download.eclipse.org/eclipse/downloads/drops4/I20220814-0600/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

The difference is that the signature of `com.ibm.icu.text.UTF16.isSurrogate(char)` changed to `com.ibm.icu.text.UTF16.isSurrogate(int)` :
baseline:
```
INVOKESTATIC com/ibm/icu/text/UTF16.isSurrogate (C)Z
```
now:
```
INVOKESTATIC com/ibm/icu/text/UTF16.isSurrogate (I)Z
```

I think that can be fixed by touching JDT bundles in question.

**Comment by akurtakov** [comment]
Thanks for handling this one Andrey!

**Comment by merks** [comment]
I see this in my workspace now so it looks like there are other incompatibilities with this version:
```
java.lang.NoClassDefFoundError: com/ibm/icu/util/StringTokenizer
	at org.eclipse.wst.sse.core.utils.StringUtils.unpack(StringUtils.java:777)
	at org.eclipse.wst.sse.core.internal.tasks.TaskScanningJob.getScannedProjects(TaskScanningJob.java:295)
	at org.eclipse.wst.sse.core.internal.tasks.TaskScanningJob.projectHasNotBeenFullyScanned(TaskScanningJob.java:152)
	at org.eclipse.wst.sse.core.internal.tasks.TaskScanningJob.addProject(TaskScanningJob.java:118)
	at org.eclipse.wst.sse.core.internal.tasks.TaskScanningScheduler.enqueue(TaskScanningScheduler.java:137)
	at org.eclipse.wst.sse.core.internal.tasks.TaskScanningScheduler.startup(TaskScanningScheduler.java:117)
	at org.eclipse.wst.sse.core.internal.SSECorePlugin.lambda$0(SSECorePlugin.java:96)
	at org.eclipse.core.runtime.jobs.Job$1.run(Job.java:166)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: com.ibm.icu.util.StringTokenizer cannot be found by org.eclipse.wst.sse.core_1.2.700.v202107272335
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:487)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 9 more
```

**Comment by iloveeclipse** [comment]
@merks : yes, this doesn't look good.

Please let discuss this on https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/476

**Pull request merged**
