### PR TITLE
Include all sources

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by mickaelistria** [comment]
Sources for assertj-core, org.apache.commons.commons-fileupload, org.apache.commons.commons-io are currently missing in the p2 repo ( https://download.eclipse.org/eclipse/updates/4.27-I-builds/I20221215-0320/plugins/ ) because they're not included in features.
If this change adds them, then it means it's good to be merged.

**Comment by mickaelistria** [comment]
Still not working... I suspect the issue is more in the aggregator doing strange things (eg using p2 mirror with multiple repo)

**Comment by mickaelistria** [comment]
I tried to capture the issue and a possible cause in Tycho land: https://github.com/eclipse-tycho/tycho/issues/1947

**Comment by mickaelistria** [comment]
With Tycho fix, this is now working.

**Comment by merks** [comment]
@mickaelistria Awesome! 🚀

**Pull request merged**
