### PR TITLE
Markdown support for JEP 467

### PR DESCRIPTION
**Pull request by stephan-herrmann**
This should get me going in https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1523

Thanks, @merks ! :)

### CODE REVIEW

**Comment by merks** [comment]
The dreaded out of memory error. 

I started another build 

https://ci.eclipse.org/platform/job/eclipse.platform.releng.aggregator/job/PR-2190/

**Comment by laeubi** [comment]
@HannesWell do we have HeapDumps for this jobs?

**Comment by HannesWell** [comment]
> @HannesWell do we have HeapDumps for this jobs?

Not by default.
Can this be enabled only if an OOM occurs?

**Comment by stephan-herrmann** [comment]
Thanks a lot @merks - I'm positively surprised to find the updated artifact already on repo.eclipse.org -> I'm all set!

**Pull request merged**
