### PR TITLE
Update target platform slf4j-api 2.0.7

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by akurtakov** [comment]
@HannesWell Is it OK not to get this update?

**Comment by HannesWell** [comment]
> @HannesWell Is it OK not to get this update?

Yes, I just wanted to mention that I already created https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/981 to update to slf4j-2.0.7. That PR is just awaiting a new release of SSHD-Mina and then we can get rid of slf4j-1 completely.
Without the new sshd version we have both the slf4j 1 and 2 api bundle which either does not work well together or is complex to set up (one probably has to configure both and has to provide two logging backends, but I have never tried that).

**Comment by HannesWell** [comment]
A new release of mina-sshd is hopefully done this week:
https://github.com/apache/mina-sshd/pull/343#issuecomment-1512923050

**Comment by HannesWell** [comment]
> No problem! I'll just abandon this. I need to update the TP for EMF's M2 and you can update this at your leisure at the appropriate time.

Thanks. AFAIKT it is really only the sshd release missing and I'm waiting for it longingly, since it seem to be the last missing piece to complete the transition to slf4j-2. I even used a self-build snapshot of sshd in #981 to verify it.

**Pull request closed without merging**
