### PR TITLE
Reduce split packages in o.e.tests

### PR DESCRIPTION
**Pull request by akurtakov**
Split packages cause a lot of troubles and this is test harness code so it's better to live without them.

### CODE REVIEW

**Comment by akurtakov** [comment]
This should reduce the issues in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2335 . 
It should also serve as pre-req for https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2368

**Comment by jukzi** [comment]
@akurtakov 
now some tests fail in i-Build
https://download.eclipse.org/eclipse/downloads/drops4/I20240923-0040/testresults/html/org.eclipse.osgi.tests_ep434I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

And locally trying to reproduce i run into this:
```
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.core.tests.harness [9]
  Unresolved requirement: Require-Bundle: org.eclipse.test.performance
    -> Bundle-SymbolicName: org.eclipse.test.performance; bundle-version="3.20.300.qualifier"; singleton:="true"
       org.eclipse.test.performance [10]
         Unresolved requirement: Import-Package: org.eclipse.test

	at org.eclipse.osgi.container.Module.start(Module.java:493)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2102)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:143)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2093)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2033)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1996)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1912)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
```
when launching PlatformURLSessionTest

reverting this PR makes the test happy again.

**Comment by akurtakov** [comment]
I will look into it tomorrow as it's public holiday here.

**Comment by jukzi** [comment]
happy

- 	King's Birthday	- Australia
-  	Day off for Independence Day - Bulgaria
-  	Blessed Rainy Day - Bhutan
-  	Kwame Nkrumah Memorial Day observed	- Ghana
-  	Autumn Equinox observed - Japan
-  	Baptism of the Prophet - Mali
-  	South Canterbury Anniversary Day - New Zealand
-  	Saudi National Day - Saudi Arabia
-  	Slovenian Sports Day - Slovenia
-  	American Indian Day - United States

**Comment by akurtakov** [comment]
I would be very thankful if you try it.

**Comment by iloveeclipse** [comment]
I've created ticket to work on: https://github.com/eclipse-platform/eclipse.platform/issues/1564.
Note, there are also ~100 osgi test failures that seem to be closely related to this.

**Pull request merged**
