### PR TITLE
Adding *.product file for update release.

### PR DESCRIPTION
**Pull request by MohananRahul**
Product files also need to be updated.

### CODE REVIEW

**Comment by akurtakov** [comment]
Is tycho-versions-plugin updating product files when run locally?

**Comment by akurtakov** [comment]
I tested locally and product files are updated:
```
[INFO] --- tycho-versions:4.0.10:set-version (default-cli) @ org.eclipse.rt.osgistarterkit.product ---
[INFO] Making changes in /home/akurtakov/git/eclipse.platform.releng.aggregator/eclipse.platform.releng.tychoeclipsebuilder/equinox.starterkit.product
[INFO]   pom.xml//project/version: 4.35.0-SNAPSHOT => 5.0.0-SNAPSHOT
[INFO]   EclipseRTOSGiStarterKit.product//product/@version: 4.35.0.qualifier => 5.0.0.qualifier
[INFO] Making changes in /home/akurtakov/git/eclipse.platform.releng.aggregator/eclipse.platform.releng.tychoeclipsebuilder
[INFO] Making changes in /home/akurtakov/git/eclipse.platform.releng.aggregator/eclipse.platform.releng.tychoeclipsebuilder/equinox-sdk
[INFO] Making changes in /home/akurtakov/git/eclipse.platform.releng.aggregator/eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests
[INFO] Making changes in /home/akurtakov/git/eclipse.platform.releng.aggregator/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository
[INFO] Making changes in /home/akurtakov/git/eclipse.platform.releng.aggregator/eclipse-platform-parent
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by akurtakov** [comment]
Merging. Let's see one more bit automated next release.

**Comment by MohananRahul** [comment]
This causing update release to fail.

**Pull request merged**
