### PR TITLE
Update target platform's jsoup to 1.16.1

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
@waynebeaton

This looks like strange set of things to review, i.e., these are projects own bundles...

**Comment by waynebeaton** [comment]
Getting the tool to consistently recognise project content in the all the form it presents itself has been a bit of a challenge. I've been tweaking it over the past few weeks and there's been a small number of regressions.

I'll add some hints to deal with these cases.

**Comment by waynebeaton** [comment]
It should work correctly now.

**Comment by merks** [comment]
@waynebeaton 

Thanks for the weekend service!  🚀

**Comment by laeubi** [comment]
@waynebeaton you probably want to take a look at The `MavenSession#getProjects()` to find out what are the projects of the current reactor.

**Comment by waynebeaton** [comment]
> @waynebeaton you probably want to take a look at The `MavenSession#getProjects()` to find out what are the projects of the current reactor.

Thanks, but using the Maven projects might help us identify project code as it is being built, but it doesn't solve the more general problem.

**Pull request merged**
