### PR TITLE
Update bouncycastle to 1.77

### PR DESCRIPTION
**Pull request by merks**
https://www.bouncycastle.org/releasenotes.html#r1rv77

### CODE REVIEW

**Comment by akurtakov** [comment]
Looking at the release notes this should be fine and we better have less conflicts with other pushing to simrel.

**Comment by iloveeclipse** [comment]
Ed, do you have anything else to merge now? If not, I will trigger yet another I Build.

**Comment by merks** [comment]
Thank you for asking! ❤️ 

No, there is nothing else.  I noticed the last two I-Builds bombed out.  Hopefully the next one is good!

**Comment by iloveeclipse** [comment]
I've checked PR's, seem to be nothing, so I've triggered IBuild...
https://ci.eclipse.org/releng/job/Builds/job/I-build-4.30/125/

**Pull request merged**
