### PR TITLE
Update batik versions to 1.16.0

### PR DESCRIPTION
**Pull request by MohananRahul**
Update batik version due to Vulnerability issues

### CODE REVIEW

**Comment by sravanlakkimsetti** [comment]
Can you please check whether you can build eclipse platform locally with this change? I don't find batik 1.16 libraries in the orbit version used here

**Comment by akurtakov** [comment]
Is this patch dead? aka should it be closed?

**Comment by akurtakov** [comment]
Even if against old branch this helps nothing but convoluting searches staying like that for weeks.

**Comment by sravanlakkimsetti** [comment]
This is a required change. But we will need to add newer Orbit version to fetch latest version of batik. Merging this as is will fail 4.23 build

**Comment by akurtakov** [comment]
So this is a work in progress ? You should be aware that Orbit is not getting much attention (if at all) lately https://git.eclipse.org/c/orbit/orbit-recipes.git/ . Wherever possible things are moving into using Maven artifacts but @jonahgraham or @merks should be the ones to clarify things about Orbit more.

**Comment by jonahgraham** [comment]
> https://git.eclipse.org/c/orbit/orbit-recipes.git/ .

This is the old URL - Orbit is on GitHub - https://github.com/eclipse/orbit

> @jonahgraham or @merks should be the ones to clarify things about Orbit more.

We (Ed and I) are meeting tomorrow to move this forward. Please keep an eye out for communications in the coming days.

**Pull request closed without merging**
