### PR TITLE
Update target platform junit dependencies

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
@akurtakov 

Assuming this tests okay, is it still okay to merge this today?

**Comment by cdietrich** [comment]
@merks will there be a similar update to the simrel maven orbit?

**Comment by cdietrich** [comment]
@merks  which repo to watch for changes to simrel/maven

**Comment by merks** [comment]
@cdietrich 

Because I've done milestone builds as well as nightly build, they are available here:

- https://download.eclipse.org/oomph/simrel-maven/2023-06
- https://download.eclipse.org/oomph/simrel-maven/milestone/latest
- https://download.eclipse.org/oomph/simrel-maven/nightly/latest
- https://download.eclipse.org/oomph/simrel-orbit/2023-06
- https://download.eclipse.org/oomph/simrel-orbit/milestone/latest
- https://download.eclipse.org/oomph/simrel-orbit/nighlty/latest

**Comment by merks** [comment]
The usual test feature qualifier touch is required and pending.

**Pull request merged**
