### PR TITLE
Update jsoup to 1.16.2

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
@akurtakov 

Is there really a freeze during m2 week?

**Comment by MohananRahul** [comment]
> @akurtakov
> 
> Is there really a freeze during m2 week?

Now I modified Calendar , previously it was M2 Signoff in calendar since M2 is lightweight no need of M2 Signoff in calendar.

**Comment by akurtakov** [comment]
> @akurtakov 
> 
> Is there really a freeze during m2 week?

No, but the calendar seems to be set for freeze.

**Comment by BeckerWdf** [comment]
> > @akurtakov
> > Is there really a freeze during m2 week?
> 
> Now I modified Calendar , previously it was M2 Signoff in calendar since M2 is lightweight no need of M2 Signoff in calendar.

It still say's it's a freeze day. See e.g.:
https://github.com/eclipse-platform/eclipse.platform/actions/runs/6586629414/job/17895304400?pr=745
That's because of the "Promotion" in the calendar.

**Pull request merged**
