### PR TITLE
Add .project file for o.e.platform.releng.prereqs.sdk

### PR DESCRIPTION
**Pull request by HannesWell**
Instead of generating it in the Oomph-setup.
@merks what do you think?

### CODE REVIEW

**Comment by merks** [comment]
That would make more sense!

**Comment by mickaelistria** [comment]
FWIW, I personally have the whole source tree imported in the workspace and don't see any benefit in having this folder open as a project over just a folder. What does that bring?

**Comment by merks** [comment]
Do you see any harm?  Oomph sets it up this way to ensure that the product itself is analyzed during targlet resolution (including its dependencies), and indirectly as a result, so that the target platform also contains this product.  But I'm perfectly with the setup doing this, though it seems strange that such an important thing is so "second class" as to be buried deeply in some folder...

**Comment by mickaelistria** [comment]
> Do you see any harm?

Not at all, I don't mind whether a .project gets added or not, I was genuinely wondering if there is some extra value I'm missing in my workflow without having a project for this folder.

**Review by iloveeclipse — APPROVED** [review]

**Comment by iloveeclipse** [comment]
> I was genuinely wondering if there is some extra value I'm missing in my workflow without having a project for this folder

There are different workflows.
I don't import all of code in one huge project, so having .project in dedicated project folders matches exact my workflow.

**Comment by HannesWell** [comment]
> FWIW, I personally have the whole source tree imported in the workspace and don't see any benefit in having this folder open as a project over just a folder. What does that bring?

Besides what has been said additionally it IMHO makes the target file more visible and therefore easier to find if one wants to access it.

**Pull request merged**
