### PR TITLE
Remove reddeer and its dependencies from the target platform

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by akurtakov** [comment]
Snakeyaml has been added for reddeer IIRC too.

**Comment by merks** [comment]
Yeah, the target platform uses only the restructured Orbit update site now!  No more ancient legacy bundles.

**Comment by HannesWell** [comment]
> Yeah, the target platform uses only the restructured Orbit update site now! No more ancient legacy bundles.

It is so great to have that all cleaned up!

**Comment by akurtakov** [comment]
Thanks @merks for finishing this one!

**Comment by laeubi** [comment]
> Thanks @merks for finishing this one!

There is still something left ;-)

- [ ] https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/019a6ab555a7509af1f2bb9a1b26618dc671e4d2/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target#L564

**Comment by merks** [comment]
> > Thanks @merks for finishing this one!
> 
> There is still something left ;-)
> 
> https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/019a6ab555a7509af1f2bb9a1b26618dc671e4d2/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target#L564


Thanks!  It's on my TODO list now.

**Pull request merged**
