### PR TITLE
Corrected eclipse p2 repo url

### PR DESCRIPTION
**Pull request by viragpurnam**
Updated the wrong eclipse repo url.
From https://download.eclipse.org/eclipse/updates/R-4.26-202211231800/ to https://download.eclipse.org/eclipse/updates/4.26/R-4.26-202211231800/

### CODE REVIEW

**Comment by merks** [comment]
@SDawley I'm not really familiar with how maintenance branches are support or maintained.  But the change here is simple and the existing URL is simply wrong...

**Comment by akurtakov** [comment]
https://accounts.eclipse.org/user/eca has to be signed as the very first step .

**Comment by viragpurnam** [comment]
> https://accounts.eclipse.org/user/eca has to be signed as the very first step .

Done

**Comment by SDawley** [comment]
I attempted to revalidate the eca but it failed.

**Review by SDawley — APPROVED** [review]

**Comment by merks** [comment]
@viragpurnam 

The ECA still does not validate:

image

Are you sure the email address you used for the GitHub account is the same email address for which you signed the ECA?

**Comment by viragpurnam** [comment]
> @viragpurnam
> 
> The ECA still does not validate:
> 
> image
> 
> Are you sure the email address you used for the GitHub account is the same email address for which you signed the ECA?

Hi @merks, Yes, I have used the same email id. Let me cross check that again.

**Comment by viragpurnam** [comment]
Hi @merks , Hi @SDawley,

I will close this PR and create a new one. Not sure what is going wrong here. Thanks.

**Pull request closed without merging**
